/*
**
** The JavaScript code is generated by atscc2js
** The starting compilation time is: 2016-12-19: 16h:40m
**
*/

/* ATSextcode_beg() */
//
// file inclusion
//
var fs = require('fs');
eval(fs.readFileSync('./../output/libatscc2js_all.js').toString());
eval(fs.readFileSync('./../CATS/PRINT/print_store_cats.js').toString());
/* ATSextcode_end() */

var _test01_statmp1

var _test01_statmp2

var _test01_statmp4

var _test01_statmp5

var _test01_statmp7

var _test01_statmp11

function
_test01_patsfun_0__closurerize()
{
  return [function(cenv) { return _test01_patsfun_0(); }];
}


function
_test01_patsfun_1__closurerize()
{
  return [function(cenv, arg0) { return _test01_patsfun_1(arg0); }];
}


function
_test01_patsfun_0()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab__test01_patsfun_0
  ats2jspre_print_string("Hello, world!");
  ats2jspre_print_newline();
  return/*_void*/;
} // end-of-function


function
_test01_patsfun_1(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab__test01_patsfun_1
  ats2jspre_print_int(arg0);
  ats2jspre_print_string(": Hello, world!");
  ats2jspre_print_newline();
  return/*_void*/;
} // end-of-function

// dynloadflag_minit
var _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_TEST_057_test01_056_dats__dynloadflag = 0;

function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_TEST_057_test01_056_dats__dynload()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // ATSdynload()
  // ATSdynloadflag_sta(_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_TEST_057_test01_056_dats__dynloadflag(43))
  if(ATSCKiseqz(_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_TEST_057_test01_056_dats__dynloadflag)) {
    _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_TEST_057_test01_056_dats__dynloadflag = 1 ; // flag is set
    _test01_statmp2 = ats2jspre_string_indexOf_2("between", "tween");
    _test01_statmp1 = ats2jspre_eq_int0_int0(_test01_statmp2, 2);
    ats2jspre_assert_errmsg_bool0(_test01_statmp1, "/home/hwxi/Research/ATS-Postiats-contrib/contrib/libatscc/libatscc2js/TEST/test01.dats: 310(line=22, offs=10) -- 351(line=22, offs=51)");
    _test01_statmp5 = ats2jspre_string_indexOf_3("between", "tween", 3);
    _test01_statmp4 = ats2jspre_lt_int0_int0(_test01_statmp5, 0);
    ats2jspre_assert_errmsg_bool0(_test01_statmp4, "/home/hwxi/Research/ATS-Postiats-contrib/contrib/libatscc/libatscc2js/TEST/test01.dats: 361(line=23, offs=10) -- 405(line=23, offs=54)");
    _test01_statmp7 = ATSPMVlazyval(_test01_patsfun_0__closurerize());
    ats2jspre_int_repeat_lazy(3, _test01_statmp7);
    _test01_statmp11 = ats2jspre_int_foreach_method(3);
    _test01_statmp11[0](_test01_statmp11, _test01_patsfun_1__closurerize());
  } // endif
  return/*_void*/;
} // end-of-function


function
test01_dynload()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_TEST_057_test01_056_dats__dynload();
  return/*_void*/;
} // end-of-function


/* ATSextcode_beg() */
test01_dynload();
process.stdout.write(ats2jspre_the_print_store_join());
/* ATSextcode_end() */

/* ****** ****** */

/* end-of-compilation-unit */
