#
# A Simple Makefile
#

######

all:: upload_html

######
#
upload_html: ; \
scp mytest.html mytest_process.php \
  ats-hwxi,ats-lang@web.sourceforge.net:htdocs/COMPILED/doc/PROJECT/MEDIUM/ATS-parse-emit/PHP/.
#
upload_DATS_PHP: ; \
scp DATS_PHP/*.js ats-hwxi,ats-lang@web.sourceforge.net:htdocs/COMPILED/doc/PROJECT/MEDIUM/ATS-parse-emit/PHP/DATS_PHP/.
#
######

###### end of [Makefile] ######
