<?php
/*
**
** The PHP code is generated by atscc2php
** The starting compilation time is: 2014-9-28: 11h:16m
**
*/

// ATSassume(GameOf24_php__card_type)

// ATSassume(GameOf24_php__cardset_type)
function
f_56__closurerize($env0, $env1, $env2, $env3)
{
  return array(function($cenv, $arg0) { return f_56($cenv[1], $cenv[2], $cenv[3], $cenv[4], $arg0); }, $env0, $env1, $env2, $env3);
}


function
GameOf24_php__card_get_val($arg0)
{
/*
  // $tmpret0
*/
  __patsflab_card_get_val:
  $tmpret0 = $arg0[0];
  return $tmpret0;
} // end-of-function


function
GameOf24_php__card_make_int($arg0)
{
/*
  // $tmpret1
  // $tmp2
  // $tmp3
*/
  __patsflab_card_make_int:
  $tmp2 = ats2phppre_int2double($arg0);
  $tmp3 = array(0, $arg0);
  $tmpret1 = array($tmp2, $tmp3);
  return $tmpret1;
} // end-of-function


function
GameOf24_php__add_card_card($arg0, $arg1)
{
/*
  // $tmpret4
  // $tmp5
  // $tmp6
*/
  __patsflab_add_card_card:
  $tmp5 = ats2phppre_add_double_double($arg0[0], $arg1[0]);
  $tmp6 = array(1, $arg0, $arg1);
  $tmpret4 = array($tmp5, $tmp6);
  return $tmpret4;
} // end-of-function


function
GameOf24_php__sub_card_card($arg0, $arg1)
{
/*
  // $tmpret7
  // $tmp8
  // $tmp9
*/
  __patsflab_sub_card_card:
  $tmp8 = ats2phppre_sub_double_double($arg0[0], $arg1[0]);
  $tmp9 = array(2, $arg0, $arg1);
  $tmpret7 = array($tmp8, $tmp9);
  return $tmpret7;
} // end-of-function


function
GameOf24_php__mul_card_card($arg0, $arg1)
{
/*
  // $tmpret10
  // $tmp11
  // $tmp12
*/
  __patsflab_mul_card_card:
  $tmp11 = ats2phppre_mul_double_double($arg0[0], $arg1[0]);
  $tmp12 = array(3, $arg0, $arg1);
  $tmpret10 = array($tmp11, $tmp12);
  return $tmpret10;
} // end-of-function


function
GameOf24_php__div_card_card($arg0, $arg1)
{
/*
  // $tmpret13
  // $tmp14
  // $tmp15
*/
  __patsflab_div_card_card:
  $tmp14 = ats2phppre_div_double_double($arg0[0], $arg1[0]);
  $tmp15 = array(4, $arg0, $arg1);
  $tmpret13 = array($tmp14, $tmp15);
  return $tmpret13;
} // end-of-function


function
GameOf24_php__fprint_card($arg0, $arg1)
{
/*
  // $tmp17
  // $tmp18
  // $tmp19
  // $tmp20
  // $tmp21
  // $tmp22
  // $tmp23
  // $tmp24
  // $tmp25
*/
  __patsflab_fprint_card:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab0:
    if(!ATSCKpat_con1($arg1[1], 0)) goto __atstmplab2;
    __atstmplab1:
    $tmp17 = $arg1[1][1];
    ats2phppre_fprint_string($arg0, "CARDint(");
    ats2phppre_fprint_int($arg0, $tmp17);
    ats2phppre_fprint_string($arg0, ")");
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab2:
    if(!ATSCKpat_con1($arg1[1], 1)) goto __atstmplab4;
    __atstmplab3:
    $tmp18 = $arg1[1][1];
    $tmp19 = $arg1[1][2];
    ats2phppre_fprint_string($arg0, "CARDadd(");
    GameOf24_php__fprint_card($arg0, $tmp18);
    ats2phppre_fprint_string($arg0, ", ");
    GameOf24_php__fprint_card($arg0, $tmp19);
    ats2phppre_fprint_string($arg0, ")");
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab4:
    if(!ATSCKpat_con1($arg1[1], 2)) goto __atstmplab6;
    __atstmplab5:
    $tmp20 = $arg1[1][1];
    $tmp21 = $arg1[1][2];
    ats2phppre_fprint_string($arg0, "CARDsub(");
    GameOf24_php__fprint_card($arg0, $tmp20);
    ats2phppre_fprint_string($arg0, ", ");
    GameOf24_php__fprint_card($arg0, $tmp21);
    ats2phppre_fprint_string($arg0, ")");
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab6:
    if(!ATSCKpat_con1($arg1[1], 3)) goto __atstmplab8;
    __atstmplab7:
    $tmp22 = $arg1[1][1];
    $tmp23 = $arg1[1][2];
    ats2phppre_fprint_string($arg0, "CARDmul(");
    GameOf24_php__fprint_card($arg0, $tmp22);
    ats2phppre_fprint_string($arg0, ", ");
    GameOf24_php__fprint_card($arg0, $tmp23);
    ats2phppre_fprint_string($arg0, ")");
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab8:
    __atstmplab9:
    $tmp24 = $arg1[1][1];
    $tmp25 = $arg1[1][2];
    ats2phppre_fprint_string($arg0, "CARDdiv(");
    GameOf24_php__fprint_card($arg0, $tmp24);
    ats2phppre_fprint_string($arg0, ", ");
    GameOf24_php__fprint_card($arg0, $tmp25);
    ats2phppre_fprint_string($arg0, ")");
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
GameOf24_php__echo_card($arg0)
{
/*
  // $tmp45
  // $tmp46
  // $tmp47
  // $tmp48
  // $tmp49
  // $tmp50
  // $tmp51
  // $tmp52
  // $tmp53
*/
  __patsflab_echo_card:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab10:
    if(!ATSCKpat_con1($arg0[1], 0)) goto __atstmplab12;
    __atstmplab11:
    $tmp45 = $arg0[1][1];
    _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo1__10__1($tmp45);
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab12:
    if(!ATSCKpat_con1($arg0[1], 1)) goto __atstmplab14;
    __atstmplab13:
    $tmp46 = $arg0[1][1];
    $tmp47 = $arg0[1][2];
    _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo5__14__1("(", $tmp46, " + ", $tmp47, ")");
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab14:
    if(!ATSCKpat_con1($arg0[1], 2)) goto __atstmplab16;
    __atstmplab15:
    $tmp48 = $arg0[1][1];
    $tmp49 = $arg0[1][2];
    _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo5__14__2("(", $tmp48, " - ", $tmp49, ")");
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab16:
    if(!ATSCKpat_con1($arg0[1], 3)) goto __atstmplab18;
    __atstmplab17:
    $tmp50 = $arg0[1][1];
    $tmp51 = $arg0[1][2];
    _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo5__14__3("(", $tmp50, " * ", $tmp51, ")");
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab18:
    __atstmplab19:
    $tmp52 = $arg0[1][1];
    $tmp53 = $arg0[1][2];
    _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo5__14__4("(", $tmp52, " / ", $tmp53, ")");
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo1__10__1($arg0)
{
/*
*/
  __patsflab_echo1:
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__1($arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__1($arg0)
{
/*
*/
  __patsflab_echo_tmp:
  ats2phppre_echo_obj($arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo5__14__1($arg0, $arg1, $arg2, $arg3, $arg4)
{
/*
*/
  __patsflab_echo5:
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__2($arg0);
  GameOf24_php__echo_card($arg1);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__3($arg2);
  GameOf24_php__echo_card($arg3);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__4($arg4);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__2($arg0)
{
/*
*/
  __patsflab_echo_tmp:
  ats2phppre_echo_obj($arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__3($arg0)
{
/*
*/
  __patsflab_echo_tmp:
  ats2phppre_echo_obj($arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__4($arg0)
{
/*
*/
  __patsflab_echo_tmp:
  ats2phppre_echo_obj($arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo5__14__2($arg0, $arg1, $arg2, $arg3, $arg4)
{
/*
*/
  __patsflab_echo5:
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__5($arg0);
  GameOf24_php__echo_card($arg1);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__6($arg2);
  GameOf24_php__echo_card($arg3);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__7($arg4);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__5($arg0)
{
/*
*/
  __patsflab_echo_tmp:
  ats2phppre_echo_obj($arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__6($arg0)
{
/*
*/
  __patsflab_echo_tmp:
  ats2phppre_echo_obj($arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__7($arg0)
{
/*
*/
  __patsflab_echo_tmp:
  ats2phppre_echo_obj($arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo5__14__3($arg0, $arg1, $arg2, $arg3, $arg4)
{
/*
*/
  __patsflab_echo5:
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__8($arg0);
  GameOf24_php__echo_card($arg1);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__9($arg2);
  GameOf24_php__echo_card($arg3);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__10($arg4);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__8($arg0)
{
/*
*/
  __patsflab_echo_tmp:
  ats2phppre_echo_obj($arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__9($arg0)
{
/*
*/
  __patsflab_echo_tmp:
  ats2phppre_echo_obj($arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__10($arg0)
{
/*
*/
  __patsflab_echo_tmp:
  ats2phppre_echo_obj($arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo5__14__4($arg0, $arg1, $arg2, $arg3, $arg4)
{
/*
*/
  __patsflab_echo5:
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__11($arg0);
  GameOf24_php__echo_card($arg1);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__12($arg2);
  GameOf24_php__echo_card($arg3);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__13($arg4);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__11($arg0)
{
/*
*/
  __patsflab_echo_tmp:
  ats2phppre_echo_obj($arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__12($arg0)
{
/*
*/
  __patsflab_echo_tmp:
  ats2phppre_echo_obj($arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__13($arg0)
{
/*
*/
  __patsflab_echo_tmp:
  ats2phppre_echo_obj($arg0);
  return/*_void*/;
} // end-of-function


function
GameOf24_php__fpprint_card($arg0, $arg1)
{
/*
  // $tmp96
  // $tmp97
  // $tmp98
  // $tmp99
  // $tmp100
  // $tmp101
  // $tmp102
  // $tmp103
  // $tmp104
*/
  __patsflab_fpprint_card:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab20:
    if(!ATSCKpat_con1($arg1[1], 0)) goto __atstmplab22;
    __atstmplab21:
    $tmp96 = $arg1[1][1];
    ats2phppre_fprint_int($arg0, $tmp96);
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab22:
    if(!ATSCKpat_con1($arg1[1], 1)) goto __atstmplab24;
    __atstmplab23:
    $tmp97 = $arg1[1][1];
    $tmp98 = $arg1[1][2];
    ats2phppre_fprint_string($arg0, "(");
    GameOf24_php__fpprint_card($arg0, $tmp97);
    ats2phppre_fprint_string($arg0, " + ");
    GameOf24_php__fpprint_card($arg0, $tmp98);
    ats2phppre_fprint_string($arg0, ")");
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab24:
    if(!ATSCKpat_con1($arg1[1], 2)) goto __atstmplab26;
    __atstmplab25:
    $tmp99 = $arg1[1][1];
    $tmp100 = $arg1[1][2];
    ats2phppre_fprint_string($arg0, "(");
    GameOf24_php__fpprint_card($arg0, $tmp99);
    ats2phppre_fprint_string($arg0, " - ");
    GameOf24_php__fpprint_card($arg0, $tmp100);
    ats2phppre_fprint_string($arg0, ")");
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab26:
    if(!ATSCKpat_con1($arg1[1], 3)) goto __atstmplab28;
    __atstmplab27:
    $tmp101 = $arg1[1][1];
    $tmp102 = $arg1[1][2];
    ats2phppre_fprint_string($arg0, "(");
    GameOf24_php__fpprint_card($arg0, $tmp101);
    ats2phppre_fprint_string($arg0, " * ");
    GameOf24_php__fpprint_card($arg0, $tmp102);
    ats2phppre_fprint_string($arg0, ")");
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab28:
    __atstmplab29:
    $tmp103 = $arg1[1][1];
    $tmp104 = $arg1[1][2];
    ats2phppre_fprint_string($arg0, "(");
    GameOf24_php__fpprint_card($arg0, $tmp103);
    ats2phppre_fprint_string($arg0, " / ");
    GameOf24_php__fpprint_card($arg0, $tmp104);
    ats2phppre_fprint_string($arg0, ")");
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
GameOf24_php__cardset_size($arg0)
{
/*
  // $tmpret121
*/
  __patsflab_cardset_size:
  $tmpret121 = PHParref_length($arg0);
  return $tmpret121;
} // end-of-function


function
GameOf24_php__cardset_make_list($arg0)
{
/*
  // $tmpret122
  // $tmp127
*/
  __patsflab_cardset_make_list:
  $tmp127 = PHParref_nil();
  $tmpret122 = loop_34($arg0, $tmp127);
  return $tmpret122;
} // end-of-function


function
loop_34($arg0, $arg1)
{
/*
  // $apy0
  // $apy1
  // $tmpret123
  // $tmp124
  // $tmp125
*/
  __patsflab_loop_34:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab30:
    if(ATSCKptriscons($arg0)) goto __atstmplab33;
    __atstmplab31:
    $tmpret123 = $arg1;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab32:
    __atstmplab33:
    $tmp124 = $arg0[0];
    $tmp125 = $arg0[1];
    PHParref_extend($arg1, $tmp124);
    // ATStailcalseq_beg
    $apy0 = $tmp125;
    $apy1 = $arg1;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab_loop_34;
    // ATStailcalseq_end
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret123;
} // end-of-function


function
GameOf24_php__cardset_get_at($arg0, $arg1)
{
/*
  // $tmpret128
*/
  __patsflab_cardset_get_at:
  $tmpret128 = PHParref_get_at($arg0, $arg1);
  return $tmpret128;
} // end-of-function


function
GameOf24_php__cardset_remove2_add1($arg0, $arg1, $arg2, $arg3)
{
/*
  // $tmpret129
  // $tmp131
  // $tmp133
  // $tmp134
  // $tmp137
*/
  __patsflab_cardset_remove2_add1:
  $tmp131 = ats2phppre_gte_int1_int1($arg1, 0);
  ats2phppre_assert_errmsg_bool1($tmp131, "/home/hwxi/research/Postiats-contrib/git/projects/SMALL/GameOf24/PHP/GameOf24_php.dats: 3844(line=235, offs=10) -- 3861(line=235, offs=27)");
  $tmp133 = ats2phppre_gte_int1_int1($arg2, 0);
  ats2phppre_assert_errmsg_bool1($tmp133, "/home/hwxi/research/Postiats-contrib/git/projects/SMALL/GameOf24/PHP/GameOf24_php.dats: 3872(line=236, offs=10) -- 3889(line=236, offs=27)");
  $tmp134 = PHParref_copy($arg0);
  PHParref_unset($tmp134, $arg1);
  PHParref_unset($tmp134, $arg2);
  $tmp137 = PHParref_values($tmp134);
  PHParref_extend($tmp137, $arg3);
  $tmpret129 = $tmp137;
  return $tmpret129;
} // end-of-function


function
GameOf24_php__echo_cardlst($arg0)
{
/*
  // $apy0
  // $tmp155
  // $tmp156
*/
  __patsflab_echo_cardlst:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab34:
    if(ATSCKptriscons($arg0)) goto __atstmplab37;
    __atstmplab35:
    // ATSINSmove_void;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab36:
    __atstmplab37:
    $tmp155 = $arg0[0];
    $tmp156 = $arg0[1];
    auxone_38($tmp155);
    // ATStailcalseq_beg
    $apy0 = $tmp156;
    $arg0 = $apy0;
    goto __patsflab_echo_cardlst;
    // ATStailcalseq_end
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
auxone_38($arg0)
{
/*
  // $tmp141
  // $tmp153
  // $tmp154
*/
  __patsflab_auxone_38:
  $tmp141 = GameOf24_php__card_get_val($arg0);
  $tmp154 = ats2phppre_add_double_double($tmp141, 0.100000000000000006);
  $tmp153 = ats2phppre_double2int($tmp154);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo4__39__1($arg0, " = ", $tmp153, "<br>\n");
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo4__39__1($arg0, $arg1, $arg2, $arg3)
{
/*
*/
  __patsflab_echo4:
  GameOf24_php__echo_card($arg0);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__14($arg1);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__15($arg2);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__16($arg3);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__14($arg0)
{
/*
*/
  __patsflab_echo_tmp:
  ats2phppre_echo_obj($arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__15($arg0)
{
/*
*/
  __patsflab_echo_tmp:
  ats2phppre_echo_obj($arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__16($arg0)
{
/*
*/
  __patsflab_echo_tmp:
  ats2phppre_echo_obj($arg0);
  return/*_void*/;
} // end-of-function


function
GameOf24_php__fpprint_cardlst($arg0, $arg1)
{
/*
  // $apy0
  // $apy1
  // $tmp166
  // $tmp167
*/
  __patsflab_fpprint_cardlst:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab38:
    if(ATSCKptriscons($arg1)) goto __atstmplab41;
    __atstmplab39:
    // ATSINSmove_void;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab40:
    __atstmplab41:
    $tmp166 = $arg1[0];
    $tmp167 = $arg1[1];
    fprone_45($arg0, $tmp166);
    // ATStailcalseq_beg
    $apy0 = $arg0;
    $apy1 = $tmp167;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab_fpprint_cardlst;
    // ATStailcalseq_end
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
fprone_45($arg0, $arg1)
{
/*
  // $tmp160
  // $tmp164
  // $tmp165
*/
  __patsflab_fprone_45:
  $tmp160 = GameOf24_php__card_get_val($arg1);
  GameOf24_php__fpprint_card($arg0, $arg1);
  ats2phppre_fprint_string($arg0, " = ");
  $tmp165 = ats2phppre_add_double_double($tmp160, 0.100000000000000006);
  $tmp164 = ats2phppre_double2int($tmp165);
  ats2phppre_fprint_int($arg0, $tmp164);
  ats2phppre_fprint_newline($arg0);
  return/*_void*/;
} // end-of-function


function
is0_46($arg0)
{
/*
  // $tmpret169
  // $tmp170
*/
  __patsflab_is0_46:
  $tmp170 = ats2phppre_abs_double($arg0);
  $tmpret169 = ats2phppre_lt_double_double($tmp170, 0.000000010000000000);
  return $tmpret169;
} // end-of-function


function
isn0_47($arg0)
{
/*
  // $tmpret171
  // $tmp172
*/
  __patsflab_isn0_47:
  $tmp172 = ats2phppre_abs_double($arg0);
  $tmpret171 = ats2phppre_gte_double_double($tmp172, 0.000000010000000000);
  return $tmpret171;
} // end-of-function


function
is24_48($arg0)
{
/*
  // $tmpret173
  // $tmp174
  // $tmp175
*/
  __patsflab_is24_48:
  $tmp175 = ats2phppre_sub_double_double($arg0, 24.0);
  $tmp174 = ats2phppre_abs_double($tmp175);
  $tmpret173 = ats2phppre_lt_double_double($tmp174, 0.000000010000000000);
  return $tmpret173;
} // end-of-function


function
card_isneqz_49($arg0)
{
/*
  // $tmpret176
  // $tmp177
*/
  __patsflab_card_isneqz_49:
  $tmp177 = GameOf24_php__card_get_val($arg0);
  $tmpret176 = isn0_47($tmp177);
  return $tmpret176;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_PHP_057_GameOf24_php_056_dats__task_reduce($arg0, $arg1)
{
/*
  // $tmpret178
  // $tmp210
*/
  __patsflab_task_reduce:
  $tmp210 = GameOf24_php__cardset_size($arg0);
  $tmpret178 = loop1_52($arg0, $tmp210, 0, $arg1);
  return $tmpret178;
} // end-of-function


function
auxdo_51($arg0, $arg1, $arg2, $arg3)
{
/*
  // $tmpret179
  // $tmp180
  // $tmp181
  // $tmp182
  // $tmp183
  // $tmp184
  // $tmp185
  // $tmp186
  // $tmp187
  // $tmp188
  // $tmp189
  // $tmp190
  // $tmp191
  // $tmp192
  // $tmp193
  // $tmp194
  // $tmp195
  // $tmp196
  // $tmp197
  // $tmp198
  // $tmp199
  // $tmp200
*/
  __patsflab_auxdo_51:
  $tmp180 = GameOf24_php__cardset_get_at($arg0, $arg1);
  $tmp181 = GameOf24_php__cardset_get_at($arg0, $arg2);
  $tmp184 = GameOf24_php__add_card_card($tmp180, $tmp181);
  $tmp183 = GameOf24_php__cardset_remove2_add1($arg0, $arg1, $arg2, $tmp184);
  $tmp182 = array($tmp183, $arg3);
  $tmp187 = GameOf24_php__sub_card_card($tmp180, $tmp181);
  $tmp186 = GameOf24_php__cardset_remove2_add1($arg0, $arg1, $arg2, $tmp187);
  $tmp185 = array($tmp186, $tmp182);
  $tmp190 = GameOf24_php__sub_card_card($tmp181, $tmp180);
  $tmp189 = GameOf24_php__cardset_remove2_add1($arg0, $arg1, $arg2, $tmp190);
  $tmp188 = array($tmp189, $tmp185);
  $tmp193 = GameOf24_php__mul_card_card($tmp180, $tmp181);
  $tmp192 = GameOf24_php__cardset_remove2_add1($arg0, $arg1, $arg2, $tmp193);
  $tmp191 = array($tmp192, $tmp188);
  $tmp195 = card_isneqz_49($tmp181);
  if($tmp195) {
    $tmp197 = GameOf24_php__div_card_card($tmp180, $tmp181);
    $tmp196 = GameOf24_php__cardset_remove2_add1($arg0, $arg1, $arg2, $tmp197);
    $tmp194 = array($tmp196, $tmp191);
  } else {
    $tmp194 = $tmp191;
  } // endif
  $tmp198 = card_isneqz_49($tmp180);
  if($tmp198) {
    $tmp200 = GameOf24_php__div_card_card($tmp181, $tmp180);
    $tmp199 = GameOf24_php__cardset_remove2_add1($arg0, $arg1, $arg2, $tmp200);
    $tmpret179 = array($tmp199, $tmp194);
  } else {
    $tmpret179 = $tmp194;
  } // endif
  return $tmpret179;
} // end-of-function


function
loop1_52($arg0, $arg1, $arg2, $arg3)
{
/*
  // $apy0
  // $apy1
  // $apy2
  // $apy3
  // $tmpret201
  // $tmp202
  // $tmp203
  // $tmp204
  // $a2rg0
  // $a2rg1
  // $a2rg2
  // $a2rg3
  // $a2rg4
  // $a2py0
  // $a2py1
  // $a2py2
  // $a2py3
  // $a2py4
  // $tmpret205
  // $tmp206
  // $tmp207
  // $tmp208
  // $tmp209
*/
  __patsflab_loop1_52:
  $tmp203 = ats2phppre_add_int0_int0($arg2, 1);
  $tmp202 = ats2phppre_lt_int0_int0($tmp203, $arg1);
  if($tmp202) {
    $tmp204 = ats2phppre_add_int0_int0($arg2, 1);
    // ATStailcalseq_beg
    $a2py0 = $arg0;
    $a2py1 = $arg1;
    $a2py2 = $arg2;
    $a2py3 = $tmp204;
    $a2py4 = $arg3;
    $a2rg0 = $a2py0;
    $a2rg1 = $a2py1;
    $a2rg2 = $a2py2;
    $a2rg3 = $a2py3;
    $a2rg4 = $a2py4;
    goto __patsflab_loop2_53;
    // ATStailcalseq_end
  } else {
    $tmpret201 = $arg3;
  } // endif
  return $tmpret201;
//
  __patsflab_loop2_53:
  $tmp206 = ats2phppre_lt_int0_int0($a2rg3, $a2rg1);
  if($tmp206) {
    $tmp207 = auxdo_51($a2rg0, $a2rg2, $a2rg3, $a2rg4);
    $tmp208 = ats2phppre_add_int0_int0($a2rg3, 1);
    // ATStailcalseq_beg
    $a2py0 = $a2rg0;
    $a2py1 = $a2rg1;
    $a2py2 = $a2rg2;
    $a2py3 = $tmp208;
    $a2py4 = $tmp207;
    $a2rg0 = $a2py0;
    $a2rg1 = $a2py1;
    $a2rg2 = $a2py2;
    $a2rg3 = $a2py3;
    $a2rg4 = $a2py4;
    goto __patsflab_loop2_53;
    // ATStailcalseq_end
  } else {
    $tmp209 = ats2phppre_add_int0_int0($a2rg2, 1);
    // ATStailcalseq_beg
    $apy0 = $a2rg0;
    $apy1 = $a2rg1;
    $apy2 = $tmp209;
    $apy3 = $a2rg4;
    $arg0 = $apy0;
    $arg1 = $apy1;
    $arg2 = $apy2;
    $arg3 = $apy3;
    goto __patsflab_loop1_52;
    // ATStailcalseq_end
  } // endif
  return $tmpret205;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_PHP_057_GameOf24_php_056_dats__tasklst_reduce($arg0, $arg1)
{
/*
  // $apy0
  // $apy1
  // $tmpret211
  // $tmp212
  // $tmp213
  // $tmp214
*/
  __patsflab_tasklst_reduce:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab42:
    if(ATSCKptrisnull($arg0)) goto __atstmplab45;
    __atstmplab43:
    $tmp212 = $arg0[0];
    $tmp213 = $arg0[1];
    $tmp214 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_PHP_057_GameOf24_php_056_dats__task_reduce($tmp212, $arg1);
    // ATStailcalseq_beg
    $apy0 = $tmp213;
    $apy1 = $tmp214;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab_tasklst_reduce;
    // ATStailcalseq_end
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab44:
    __atstmplab45:
    $tmpret211 = $arg1;
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret211;
} // end-of-function


function
GameOf24_php__GameOf24_play($arg0, $arg1, $arg2, $arg3)
{
/*
  // $tmpret215
  // $tmp216
  // $tmp217
  // $tmp218
  // $tmp219
  // $tmp221
  // $tmp222
  // $tmp223
  // $tmp224
  // $tmp225
  // $tmp226
  // $tmp227
  // $tmp228
  // $tmp229
  // $tmp230
  // $tmp231
  // $tmp232
  // $tmp233
  // $tmp234
  // $tmp235
  // $tmp236
  // $tmp237
  // $tmp238
  // $tmp246
  // $tmp247
*/
  __patsflab_GameOf24_play:
  $tmp216 = GameOf24_php__card_make_int($arg0);
  $tmp217 = GameOf24_php__card_make_int($arg1);
  $tmp218 = GameOf24_php__card_make_int($arg2);
  $tmp219 = GameOf24_php__card_make_int($arg3);
  $tmp225 = null;
  $tmp224 = array($tmp219, $tmp225);
  $tmp223 = array($tmp218, $tmp224);
  $tmp222 = array($tmp217, $tmp223);
  $tmp221 = array($tmp216, $tmp222);
  $tmp226 = GameOf24_php__cardset_make_list($tmp221);
  $tmp227 = GameOf24_php__cardset_size($tmp226);
  $tmp229 = null;
  $tmp228 = array($tmp226, $tmp229);
  $tmp230 = null;
  $tmp231 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_PHP_057_GameOf24_php_056_dats__tasklst_reduce($tmp228, $tmp230);
  $tmp232 = ats2phppre_list_reverse($tmp231);
  $tmp233 = null;
  $tmp234 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_PHP_057_GameOf24_php_056_dats__tasklst_reduce($tmp232, $tmp233);
  $tmp235 = ats2phppre_list_reverse($tmp234);
  $tmp236 = null;
  $tmp237 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_PHP_057_GameOf24_php_056_dats__tasklst_reduce($tmp235, $tmp236);
  $tmp238 = ats2phppre_list_reverse($tmp237);
  $tmp247 = null;
  $tmp246 = filter_57($tmp238, $tmp247);
  $tmpret215 = ats2phppre_list_reverse($tmp246);
  return $tmpret215;
} // end-of-function


function
f_56($env0, $env1, $env2, $env3, $arg0)
{
/*
  // $tmpret220
*/
  __patsflab_f_56:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab46:
    if(!ATSCKpat_int($arg0, 0)) goto __atstmplab48;
    __atstmplab47:
    $tmpret220 = $env0;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab48:
    if(!ATSCKpat_int($arg0, 1)) goto __atstmplab50;
    __atstmplab49:
    $tmpret220 = $env1;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab50:
    if(!ATSCKpat_int($arg0, 2)) goto __atstmplab52;
    __atstmplab51:
    $tmpret220 = $env2;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab52:
    $tmpret220 = $env3;
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret220;
} // end-of-function


function
filter_57($arg0, $arg1)
{
/*
  // $apy0
  // $apy1
  // $tmpret239
  // $tmp240
  // $tmp241
  // $tmp242
  // $tmp243
  // $tmp244
  // $tmp245
*/
  __patsflab_filter_57:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab53:
    if(ATSCKptriscons($arg0)) goto __atstmplab56;
    __atstmplab54:
    $tmpret239 = $arg1;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab55:
    __atstmplab56:
    $tmp240 = $arg0[0];
    $tmp241 = $arg0[1];
    $tmp242 = GameOf24_php__cardset_get_at($tmp240, 0);
    $tmp243 = GameOf24_php__card_get_val($tmp242);
    $tmp245 = is24_48($tmp243);
    if($tmp245) {
      $tmp244 = array($tmp242, $arg1);
    } else {
      $tmp244 = $arg1;
    } // endif
    // ATStailcalseq_beg
    $apy0 = $tmp241;
    $apy1 = $tmp244;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab_filter_57;
    // ATStailcalseq_end
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret239;
} // end-of-function


function
GameOf24_play2($arg0, $arg1, $arg2, $arg3)
{
/*
  // $tmp249
*/
  __patsflab_GameOf24_play2:
  $tmp249 = GameOf24_php__GameOf24_play($arg0, $arg1, $arg2, $arg3);
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab57:
    if(ATSCKptrisnull($tmp249)) goto __atstmplab60;
    __atstmplab58:
    GameOf24_php__echo_cardlst($tmp249);
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab59:
    __atstmplab60:
    _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo1__10__2("No solution is found.");
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo1__10__2($arg0)
{
/*
*/
  __patsflab_echo1:
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__17($arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__echo_tmp__12__17($arg0)
{
/*
*/
  __patsflab_echo_tmp:
  ats2phppre_echo_obj($arg0);
  return/*_void*/;
} // end-of-function


function
GameOf24_php_main0_php()
{
/*
  // $tmp253
  // $tmp265
  // $tmp277
  // $tmp289
*/
  __patsflab_main0_php:
  $tmp253 = GameOf24_php__GameOf24_play(3, 3, 8, 8);
  ats2phppre_fprint_string(STDOUT, "play(");
  ats2phppre_fprint_int(STDOUT, 3);
  ats2phppre_fprint_string(STDOUT, ", ");
  ats2phppre_fprint_int(STDOUT, 3);
  ats2phppre_fprint_string(STDOUT, ", ");
  ats2phppre_fprint_int(STDOUT, 8);
  ats2phppre_fprint_string(STDOUT, ", ");
  ats2phppre_fprint_int(STDOUT, 8);
  ats2phppre_fprint_string(STDOUT, "):");
  ats2phppre_fprint_newline(STDOUT);
  GameOf24_php__fpprint_cardlst(STDOUT, $tmp253);
  $tmp265 = GameOf24_php__GameOf24_play(4, 4, 10, 10);
  ats2phppre_fprint_string(STDOUT, "play(");
  ats2phppre_fprint_int(STDOUT, 4);
  ats2phppre_fprint_string(STDOUT, ", ");
  ats2phppre_fprint_int(STDOUT, 4);
  ats2phppre_fprint_string(STDOUT, ", ");
  ats2phppre_fprint_int(STDOUT, 10);
  ats2phppre_fprint_string(STDOUT, ", ");
  ats2phppre_fprint_int(STDOUT, 10);
  ats2phppre_fprint_string(STDOUT, "):");
  ats2phppre_fprint_newline(STDOUT);
  GameOf24_php__fpprint_cardlst(STDOUT, $tmp265);
  $tmp277 = GameOf24_php__GameOf24_play(5, 5, 7, 11);
  ats2phppre_fprint_string(STDOUT, "play(");
  ats2phppre_fprint_int(STDOUT, 5);
  ats2phppre_fprint_string(STDOUT, ", ");
  ats2phppre_fprint_int(STDOUT, 5);
  ats2phppre_fprint_string(STDOUT, ", ");
  ats2phppre_fprint_int(STDOUT, 7);
  ats2phppre_fprint_string(STDOUT, ", ");
  ats2phppre_fprint_int(STDOUT, 11);
  ats2phppre_fprint_string(STDOUT, "):");
  ats2phppre_fprint_newline(STDOUT);
  GameOf24_php__fpprint_cardlst(STDOUT, $tmp277);
  $tmp289 = GameOf24_php__GameOf24_play(3, 5, 7, 13);
  ats2phppre_fprint_string(STDOUT, "play(");
  ats2phppre_fprint_int(STDOUT, 3);
  ats2phppre_fprint_string(STDOUT, ", ");
  ats2phppre_fprint_int(STDOUT, 5);
  ats2phppre_fprint_string(STDOUT, ", ");
  ats2phppre_fprint_int(STDOUT, 7);
  ats2phppre_fprint_string(STDOUT, ", ");
  ats2phppre_fprint_int(STDOUT, 13);
  ats2phppre_fprint_string(STDOUT, "):");
  ats2phppre_fprint_newline(STDOUT);
  GameOf24_php__fpprint_cardlst(STDOUT, $tmp289);
  return/*_void*/;
} // end-of-function

/* ****** ****** */

/* end-of-compilation-unit */
?>
