%%%%%%
%%
%% The Erlang code is generated by atscc2erl
%% The starting compilation time is: 2016-12-25: 17h:43m
%%
%%%%%%

%%fun%%
libats2erl_session_chanpos_sslist(Arg0) ->
%{
%%
%% knd = 0
%% var Tmpret0
%% var Tmp1
%% var Tmp2
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_chanpos_sslist,
  Tmp1 = libats2erl_session_chanpos0_recv(Arg0),
  Tmp2 = ats2erlpre_eq_int0_int0(Tmp1, 0),
  if
    Tmp2 ->
      0;
    %% if-then
    true ->
      1
    %% if-else
  end.
%} // end-of-function


%%fun%%
libats2erl_session_channeg_sslist_nil(Arg0) ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_channeg_sslist_nil,
  libats2erl_session_channeg0_recv(Arg0, 0).
%} // end-of-function


%%fun%%
libats2erl_session_channeg_sslist_cons(Arg0) ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_channeg_sslist_cons,
  libats2erl_session_channeg0_recv(Arg0, 1).
%} // end-of-function


%%fun%%
f_057_Users_057_RyanKing_057_ATS2_055_contrib_057_contrib_057_libatscc_057_libatscc2erl_057_Session_057_SATS_057_co_055_sslist_056_sats__channeg_sslist_nil_close(Arg0) ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_channeg_sslist_nil_close,
  libats2erl_session_channeg_sslist_nil(Arg0),
  libats2erl_session_channeg_nil_close(Arg0).
%} // end-of-function

%%%%%%
%%
%% end-of-compilation-unit
%%
%%%%%%
