%%%%%%
%%
%% The Erlang code is generated by atscc2erl
%% The starting compilation time is: 2016-12-25: 17h:43m
%%
%%%%%%

%%fun%%
f_libats2erl_session_ssarray_patsfun_5__closurerize(XEnv0) -> 
%{
  {fun({_, Cenv1}, XArg0) -> f_libats2erl_session_ssarray_patsfun_5(Cenv1, XArg0) end, XEnv0}.
%}


%%fun%%
f_libats2erl_session_ssarray_patsfun_8__closurerize(XEnv0) -> 
%{
  {fun({_, Cenv1}, XArg0) -> f_libats2erl_session_ssarray_patsfun_8(Cenv1, XArg0) end, XEnv0}.
%}


%%fun%%
f_057_Users_057_RyanKing_057_ATS2_055_contrib_057_contrib_057_libatscc_057_libatscc2erl_057_Session_057_SATS_057_ssarray_056_sats__chanpos_arrsz(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_chanpos_arrsz,
  libats2erl_session_chanpos_send(Arg0, Arg1).
%} // end-of-function


%%fun%%
f_057_Users_057_RyanKing_057_ATS2_055_contrib_057_contrib_057_libatscc_057_libatscc2erl_057_Session_057_SATS_057_ssarray_056_sats__channeg_arrsz(Arg0) ->
%{
%%
%% knd = 0
%% var Tmpret1
%% var Tmp2
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_channeg_arrsz,
  Tmp2 = libats2erl_session_channeg_send(Arg0),
  Tmp2.
%} // end-of-function


%%fun%%
f_057_Users_057_RyanKing_057_ATS2_055_contrib_057_contrib_057_libatscc_057_libatscc2erl_057_Session_057_SATS_057_ssarray_056_sats__ssarray2list(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret3
%% var Tmp4
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_ssarray2list,
  Tmp4 = f_057_Users_057_RyanKing_057_ATS2_055_contrib_057_contrib_057_libatscc_057_libatscc2erl_057_Session_057_SATS_057_ssarray_056_sats__ssarray2list_vt(Arg0, Arg1),
  Tmp4.
%} // end-of-function


%%fun%%
f_057_Users_057_RyanKing_057_ATS2_055_contrib_057_contrib_057_libatscc_057_libatscc2erl_057_Session_057_SATS_057_ssarray_056_sats__list2ssarray(Arg0) ->
%{
%%
%% knd = 0
%% var Tmpret5
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_list2ssarray,
  libats2erl_session_channeg_create(f_libats2erl_session_ssarray_patsfun_5__closurerize(Arg0)).
%} // end-of-function


%%fun%%
f_libats2erl_session_ssarray_fserv_4(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmp7
%% var Tmp8
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab__libats2erl_session_ssarray_fserv_4,
  begin
  Casefunx1 =
  fun (Casefun, Tmplab) ->
    %switch(Tmplab) {
    case Tmplab of
      %% ATSbranchseq_beg
      1 ->
      if(?ATSCKptriscons(Arg1)) -> Casefun(Casefun, 4); true ->
        Casefun(Casefun, 2)
      end;
      2 ->
      libats2erl_session_chanpos_nil_wait(Arg0);
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      3 ->
      Casefun(Casefun, 4);
      4 ->
      Tmp7 = ?ATSSELcon(Arg1, 0),
      Tmp8 = ?ATSSELcon(Arg1, 1),
      libats2erl_session_chanpos_send(Arg0, Tmp7),
      f_libats2erl_session_ssarray_fserv_4(Arg0, Tmp8);
      %% ATSbranchseq_end
      _ -> atscc2erl_caseof_deadcode(?FILE, ?LINE)
    end %% endcase
    %} // end-of-switch
  end, %% endfun
  Casefunx1(Casefunx1, 1)
  end.
%} // end-of-function


%%fun%%
f_libats2erl_session_ssarray_patsfun_5(Env0, Arg0) ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab__libats2erl_session_ssarray_patsfun_5,
  f_libats2erl_session_ssarray_fserv_4(Arg0, Env0).
%} // end-of-function


%%fun%%
f_057_Users_057_RyanKing_057_ATS2_055_contrib_057_contrib_057_libatscc_057_libatscc2erl_057_Session_057_SATS_057_ssarray_056_sats__list2ssarray_vt(Arg0) ->
%{
%%
%% knd = 0
%% var Tmpret11
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_list2ssarray_vt,
  libats2erl_session_channeg_create(f_libats2erl_session_ssarray_patsfun_8__closurerize(Arg0)).
%} // end-of-function


%%fun%%
f_libats2erl_session_ssarray_fserv_7(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmp13
%% var Tmp14
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab__libats2erl_session_ssarray_fserv_7,
  begin
  Casefunx1 =
  fun (Casefun, Tmplab) ->
    %switch(Tmplab) {
    case Tmplab of
      %% ATSbranchseq_beg
      1 ->
      if(?ATSCKptriscons(Arg1)) -> Casefun(Casefun, 4); true ->
        Casefun(Casefun, 2)
      end;
      2 ->
      libats2erl_session_chanpos_nil_wait(Arg0);
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      3 ->
      Casefun(Casefun, 4);
      4 ->
      Tmp13 = ?ATSSELcon(Arg1, 0),
      Tmp14 = ?ATSSELcon(Arg1, 1),
      %% ATSINSfreecon(Arg1);,
      libats2erl_session_chanpos_send(Arg0, Tmp13),
      f_libats2erl_session_ssarray_fserv_7(Arg0, Tmp14);
      %% ATSbranchseq_end
      _ -> atscc2erl_caseof_deadcode(?FILE, ?LINE)
    end %% endcase
    %} // end-of-switch
  end, %% endfun
  Casefunx1(Casefunx1, 1)
  end.
%} // end-of-function


%%fun%%
f_libats2erl_session_ssarray_patsfun_8(Env0, Arg0) ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab__libats2erl_session_ssarray_patsfun_8,
  f_libats2erl_session_ssarray_fserv_7(Arg0, Env0).
%} // end-of-function


%%fun%%
f_057_Users_057_RyanKing_057_ATS2_055_contrib_057_contrib_057_libatscc_057_libatscc2erl_057_Session_057_SATS_057_ssarray_056_sats__ssarray2list_vt(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret17
%% var Tmp18
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_ssarray2list_vt,
  Tmp18 = f_057_Users_057_RyanKing_057_ATS2_055_contrib_057_contrib_057_libatscc_057_libatscc2erl_057_Session_057_SATS_057_ssarray_056_sats__channeg_array_takeout_list(Arg0, Arg1),
  libats2erl_session_channeg_nil_close(Arg0),
  Tmp18.
%} // end-of-function


%%fun%%
f_057_Users_057_RyanKing_057_ATS2_055_contrib_057_contrib_057_libatscc_057_libatscc2erl_057_Session_057_SATS_057_ssarray_056_sats__channeg_array_takeout_list(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret20
%% var Tmp30
%% var Tmp31
%% var Tmp32
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_channeg_array_takeout_list,
  Tmp31 = atscc2erl_null,
  Tmp30 = f_libats2erl_session_ssarray_loop_12(Arg0, Arg1, Tmp31),
  Tmp32 = atscc2erl_null,
  f_libats2erl_session_ssarray_revapp_11(Tmp30, Tmp32).
%} // end-of-function


%%fun%%
f_libats2erl_session_ssarray_revapp_11(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret21
%% var Tmp22
%% var Tmp23
%% var Tmp24
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab__libats2erl_session_ssarray_revapp_11,
  begin
  Casefunx1 =
  fun (Casefun, Tmplab) ->
    %switch(Tmplab) {
    case Tmplab of
      %% ATSbranchseq_beg
      1 ->
      if(?ATSCKptriscons(Arg0)) -> Casefun(Casefun, 4); true ->
        Casefun(Casefun, 2)
      end;
      2 ->
      Arg1;
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      3 ->
      Casefun(Casefun, 4);
      4 ->
      Tmp22 = ?ATSSELcon(Arg0, 0),
      Tmp23 = ?ATSSELcon(Arg0, 1),
      %% ATSINSfreecon(Arg0);,
      Tmp24 = {Tmp22, Arg1},
      f_libats2erl_session_ssarray_revapp_11(Tmp23, Tmp24);
      %% ATSbranchseq_end
      _ -> atscc2erl_caseof_deadcode(?FILE, ?LINE)
    end %% endcase
    %} // end-of-switch
  end, %% endfun
  Casefunx1(Casefunx1, 1)
  end.
%} // end-of-function


%%fun%%
f_libats2erl_session_ssarray_loop_12(Arg0, Arg1, Arg2) ->
%{
%%
%% knd = 0
%% var Tmpret25
%% var Tmp26
%% var Tmp27
%% var Tmp28
%% var Tmp29
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab__libats2erl_session_ssarray_loop_12,
  Tmp26 = ats2erlpre_gt_int1_int1(Arg1, 0),
  if
    Tmp26 ->
      Tmp27 = libats2erl_session_channeg_send(Arg0),
      Tmp28 = ats2erlpre_sub_int1_int1(Arg1, 1),
      Tmp29 = {Tmp27, Arg2},
      f_libats2erl_session_ssarray_loop_12(Arg0, Tmp28, Tmp29);
    %% if-then
    true ->
      Arg2
    %% if-else
  end.
%} // end-of-function

%%%%%%
%%
%% end-of-compilation-unit
%%
%%%%%%
