%%%%%%
%%
%% The Erlang code is generated by atscc2erl
%% The starting compilation time is: 2016-12-25: 17h:43m
%%
%%%%%%

%%fun%%
f_libats2erl_session_sslist_patsfun_6__closurerize(XEnv0) -> 
%{
  {fun({_, Cenv1}, XArg0) -> f_libats2erl_session_sslist_patsfun_6(Cenv1, XArg0) end, XEnv0}.
%}


%%fun%%
libats2erl_session_chanpos_sslist_nil(Arg0) ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_chanpos_sslist_nil,
  libats2erl_session_chanpos0_send(Arg0, 0).
%} // end-of-function


%%fun%%
libats2erl_session_chanpos_sslist_cons(Arg0) ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_chanpos_sslist_cons,
  libats2erl_session_chanpos0_send(Arg0, 1).
%} // end-of-function


%%fun%%
f_057_Users_057_RyanKing_057_ATS2_055_contrib_057_contrib_057_libatscc_057_libatscc2erl_057_Session_057_SATS_057_sslist_056_sats__chanpos_sslist_nil_wait(Arg0) ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_chanpos_sslist_nil_wait,
  libats2erl_session_chanpos_sslist_nil(Arg0),
  libats2erl_session_chanpos_nil_wait(Arg0).
%} // end-of-function


%%fun%%
libats2erl_session_channeg_sslist(Arg0) ->
%{
%%
%% knd = 0
%% var Tmpret4
%% var Tmp5
%% var Tmp6
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_channeg_sslist,
  Tmp5 = libats2erl_session_channeg0_send(Arg0),
  Tmp6 = ats2erlpre_eq_int0_int0(Tmp5, 0),
  if
    Tmp6 ->
      0;
    %% if-then
    true ->
      1
    %% if-else
  end.
%} // end-of-function


%%fun%%
f_057_Users_057_RyanKing_057_ATS2_055_contrib_057_contrib_057_libatscc_057_libatscc2erl_057_Session_057_SATS_057_sslist_056_sats__list2sslist(Arg0) ->
%{
%%
%% knd = 0
%% var Tmpret7
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_list2sslist,
  libats2erl_session_channeg_create(f_libats2erl_session_sslist_patsfun_6__closurerize(Arg0)).
%} // end-of-function


%%fun%%
f_libats2erl_session_sslist_fserv_5(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmp9
%% var Tmp10
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab__libats2erl_session_sslist_fserv_5,
  begin
  Casefunx1 =
  fun (Casefun, Tmplab) ->
    %switch(Tmplab) {
    case Tmplab of
      %% ATSbranchseq_beg
      1 ->
      if(?ATSCKptriscons(Arg1)) -> Casefun(Casefun, 4); true ->
        Casefun(Casefun, 2)
      end;
      2 ->
      libats2erl_session_chanpos_sslist_nil(Arg0),
      libats2erl_session_chanpos_nil_wait(Arg0);
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      3 ->
      Casefun(Casefun, 4);
      4 ->
      Tmp9 = ?ATSSELcon(Arg1, 0),
      Tmp10 = ?ATSSELcon(Arg1, 1),
      libats2erl_session_chanpos_sslist_cons(Arg0),
      libats2erl_session_chanpos_send(Arg0, Tmp9),
      f_libats2erl_session_sslist_fserv_5(Arg0, Tmp10);
      %% ATSbranchseq_end
      _ -> atscc2erl_caseof_deadcode(?FILE, ?LINE)
    end %% endcase
    %} // end-of-switch
  end, %% endfun
  Casefunx1(Casefunx1, 1)
  end.
%} // end-of-function


%%fun%%
f_libats2erl_session_sslist_patsfun_6(Env0, Arg0) ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab__libats2erl_session_sslist_patsfun_6,
  f_libats2erl_session_sslist_fserv_5(Arg0, Env0).
%} // end-of-function


%%fun%%
f_057_Users_057_RyanKing_057_ATS2_055_contrib_057_contrib_057_libatscc_057_libatscc2erl_057_Session_057_SATS_057_sslist_056_sats__sslist2list(Arg0) ->
%{
%%
%% knd = 0
%% var Tmpret15
%% var Tmp21
%% var Tmp22
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_sslist2list,
  Tmp22 = atscc2erl_null,
  Tmp21 = f_libats2erl_session_sslist_loop_8(Arg0, Tmp22),
  ats2erlpre_list_reverse(Tmp21).
%} // end-of-function


%%fun%%
f_libats2erl_session_sslist_loop_8(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret16
%% var Tmp17
%% var Tmp19
%% var Tmp20
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab__libats2erl_session_sslist_loop_8,
  Tmp17 = libats2erl_session_channeg_sslist(Arg0),
  begin
  Casefunx1 =
  fun (Casefun, Tmplab) ->
    %switch(Tmplab) {
    case Tmplab of
      %% ATSbranchseq_beg
      1 ->
      if(not(?ATSCKpat_con0(Tmp17, 0))) -> Casefun(Casefun, 4); true ->
        Casefun(Casefun, 2)
      end;
      2 ->
      libats2erl_session_channeg_nil_close(Arg0),
      Arg1;
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      3 ->
      Casefun(Casefun, 4);
      4 ->
      Tmp19 = libats2erl_session_channeg_send(Arg0),
      Tmp20 = {Tmp19, Arg1},
      f_libats2erl_session_sslist_loop_8(Arg0, Tmp20);
      %% ATSbranchseq_end
      _ -> atscc2erl_caseof_deadcode(?FILE, ?LINE)
    end %% endcase
    %} // end-of-switch
  end, %% endfun
  Casefunx1(Casefunx1, 1)
  end.
%} // end-of-function

%%%%%%
%%
%% end-of-compilation-unit
%%
%%%%%%
