;;;;;;
;;
;; The Clojure code is generated by atscc2clj
;; The starting compilation time is: 2016-12-25: 17h:42m
;;
;;;;;;
(declare _ats2cljpre_ML_list0_loop_7)
(declare _ats2cljpre_ML_list0_aux_23)
(declare _ats2cljpre_ML_list0_patsfun_26)
(declare _ats2cljpre_ML_list0_patsfun_29)
(declare _ats2cljpre_ML_list0_patsfun_32)
(declare _ats2cljpre_ML_list0_patsfun_35)
(declare _ats2cljpre_ML_list0_patsfun_39)
(declare _ats2cljpre_ML_list0_patsfun_42)
(declare _ats2cljpre_ML_list0_patsfun_45)
(declare _ats2cljpre_ML_list0_patsfun_48)
(declare _ats2cljpre_ML_list0_patsfun_51)
(declare _ats2cljpre_ML_list0_aux_55)
(declare _ats2cljpre_ML_list0_aux_57)
(declare _ats2cljpre_ML_list0_patsfun_59)
(declare _ats2cljpre_ML_list0_aux_61)
(declare _ats2cljpre_ML_list0_aux_63)
(declare _ats2cljpre_ML_list0_auxmain_69)
(declare _ats2cljpre_ML_list0_patsfun_70)
(declare _ats2cljpre_ML_list0_patsfun_71)
(declare ats2cljpre_stream_vt_make_nil__72__1)
(declare _ats2cljpre_ML_list0_patsfun_73__73__1)
(declare _ats2cljpre_ML_list0_auxmain_77)
(declare _ats2cljpre_ML_list0_patsfun_78)
(declare _ats2cljpre_ML_list0_patsfun_79)
(declare _ats2cljpre_ML_list0_patsfun_80)
(declare ats2cljpre_stream_vt_make_nil__72__2)
(declare _ats2cljpre_ML_list0_patsfun_73__73__2)
(declare ats2cljpre_ML_list0_head_opt)
(declare ats2cljpre_ML_list0_tail_opt)
(declare ats2cljpre_ML_list0_length)
(declare ats2cljpre_ML_list0_last_opt)
(declare _ats2cljpre_ML_list0_loop_7)
(declare ats2cljpre_ML_list0_get_at_opt)
(declare ats2cljpre_ML_list0_make_intrange_2)
(declare ats2cljpre_ML_list0_make_intrange_3)
(declare ats2cljpre_ML_list0_snoc)
(declare ats2cljpre_ML_list0_extend)
(declare ats2cljpre_ML_list0_append)
(declare ats2cljpre_ML_list0_reverse)
(declare ats2cljpre_ML_list0_reverse_append)
(declare ats2cljpre_ML_list0_concat)
(declare ats2cljpre_ML_list0_remove_at_opt)
(declare _ats2cljpre_ML_list0_aux_23)
(declare ats2cljpre_ML_list0_exists)
(declare ats2cljpre_ML_list0_exists_method)
(declare _ats2cljpre_ML_list0_patsfun_26)
(declare ats2cljpre_ML_list0_iexists)
(declare ats2cljpre_ML_list0_iexists_method)
(declare _ats2cljpre_ML_list0_patsfun_29)
(declare ats2cljpre_ML_list0_forall)
(declare ats2cljpre_ML_list0_forall_method)
(declare _ats2cljpre_ML_list0_patsfun_32)
(declare ats2cljpre_ML_list0_iforall)
(declare ats2cljpre_ML_list0_iforall_method)
(declare _ats2cljpre_ML_list0_patsfun_35)
(declare ats2cljpre_ML_list0_app)
(declare ats2cljpre_ML_list0_foreach)
(declare ats2cljpre_ML_list0_foreach_method)
(declare _ats2cljpre_ML_list0_patsfun_39)
(declare ats2cljpre_ML_list0_iforeach)
(declare ats2cljpre_ML_list0_iforeach_method)
(declare _ats2cljpre_ML_list0_patsfun_42)
(declare ats2cljpre_ML_list0_rforeach)
(declare ats2cljpre_ML_list0_rforeach_method)
(declare _ats2cljpre_ML_list0_patsfun_45)
(declare ats2cljpre_ML_list0_filter)
(declare ats2cljpre_ML_list0_filter_method)
(declare _ats2cljpre_ML_list0_patsfun_48)
(declare ats2cljpre_ML_list0_map)
(declare ats2cljpre_ML_list0_map_method)
(declare _ats2cljpre_ML_list0_patsfun_51)
(declare ats2cljpre_ML_list0_mapcons)
(declare ats2cljpre_ML_list0_find_opt)
(declare ats2cljpre_ML_list0_zip)
(declare _ats2cljpre_ML_list0_aux_55)
(declare ats2cljpre_ML_list0_zipwith)
(declare _ats2cljpre_ML_list0_aux_57)
(declare ats2cljpre_ML_list0_zipwith_method)
(declare _ats2cljpre_ML_list0_patsfun_59)
(declare ats2cljpre_ML_list0_foldleft)
(declare _ats2cljpre_ML_list0_aux_61)
(declare ats2cljpre_ML_list0_foldright)
(declare _ats2cljpre_ML_list0_aux_63)
(declare ats2cljpre_ML_list0_sort_2)
(declare ats2cljpre_ML_streamize_list0_zip)
(declare ats2cljpre_ML_streamize_list0_cross)
(declare ats2cljpre_ML_streamize_list0_nchoose)
(declare _ats2cljpre_ML_list0_auxmain_69)
(declare _ats2cljpre_ML_list0_patsfun_70)
(declare _ats2cljpre_ML_list0_patsfun_71)
(declare ats2cljpre_stream_vt_make_nil__72__1)
(declare _ats2cljpre_ML_list0_patsfun_73__73__1)
(declare ats2cljpre_ML_streamize_list0_nchoose_rest)
(declare _ats2cljpre_ML_list0_auxmain_77)
(declare _ats2cljpre_ML_list0_patsfun_78)
(declare _ats2cljpre_ML_list0_patsfun_79)
(declare _ats2cljpre_ML_list0_patsfun_80)
(declare ats2cljpre_stream_vt_make_nil__72__2)
(declare _ats2cljpre_ML_list0_patsfun_73__73__2)
;;;;;;


(defn
_ats2cljpre_ML_list0_patsfun_26__closurerize[xenv0]
;;%{
  (list (fn[_fcenvs_ xarg0](_ats2cljpre_ML_list0_patsfun_26 (ATSCCget_1 _fcenvs_) xarg0)) xenv0)
;;%}
) ;; end-of-defn


(defn
_ats2cljpre_ML_list0_patsfun_29__closurerize[xenv0]
;;%{
  (list (fn[_fcenvs_ xarg0](_ats2cljpre_ML_list0_patsfun_29 (ATSCCget_1 _fcenvs_) xarg0)) xenv0)
;;%}
) ;; end-of-defn


(defn
_ats2cljpre_ML_list0_patsfun_32__closurerize[xenv0]
;;%{
  (list (fn[_fcenvs_ xarg0](_ats2cljpre_ML_list0_patsfun_32 (ATSCCget_1 _fcenvs_) xarg0)) xenv0)
;;%}
) ;; end-of-defn


(defn
_ats2cljpre_ML_list0_patsfun_35__closurerize[xenv0]
;;%{
  (list (fn[_fcenvs_ xarg0](_ats2cljpre_ML_list0_patsfun_35 (ATSCCget_1 _fcenvs_) xarg0)) xenv0)
;;%}
) ;; end-of-defn


(defn
_ats2cljpre_ML_list0_patsfun_39__closurerize[xenv0]
;;%{
  (list (fn[_fcenvs_ xarg0](_ats2cljpre_ML_list0_patsfun_39 (ATSCCget_1 _fcenvs_) xarg0)) xenv0)
;;%}
) ;; end-of-defn


(defn
_ats2cljpre_ML_list0_patsfun_42__closurerize[xenv0]
;;%{
  (list (fn[_fcenvs_ xarg0](_ats2cljpre_ML_list0_patsfun_42 (ATSCCget_1 _fcenvs_) xarg0)) xenv0)
;;%}
) ;; end-of-defn


(defn
_ats2cljpre_ML_list0_patsfun_45__closurerize[xenv0]
;;%{
  (list (fn[_fcenvs_ xarg0](_ats2cljpre_ML_list0_patsfun_45 (ATSCCget_1 _fcenvs_) xarg0)) xenv0)
;;%}
) ;; end-of-defn


(defn
_ats2cljpre_ML_list0_patsfun_48__closurerize[xenv0]
;;%{
  (list (fn[_fcenvs_ xarg0](_ats2cljpre_ML_list0_patsfun_48 (ATSCCget_1 _fcenvs_) xarg0)) xenv0)
;;%}
) ;; end-of-defn


(defn
_ats2cljpre_ML_list0_patsfun_51__closurerize[xenv0]
;;%{
  (list (fn[_fcenvs_ xarg0](_ats2cljpre_ML_list0_patsfun_51 (ATSCCget_1 _fcenvs_) xarg0)) xenv0)
;;%}
) ;; end-of-defn


(defn
_ats2cljpre_ML_list0_patsfun_59__closurerize[xenv0 xenv1]
;;%{
  (list (fn[_fcenvs_ xarg0](_ats2cljpre_ML_list0_patsfun_59 (ATSCCget_1 _fcenvs_) (ATSCCget_2 _fcenvs_) xarg0)) xenv0 xenv1)
;;%}
) ;; end-of-defn


(defn
_ats2cljpre_ML_list0_patsfun_70__closurerize[xenv0 xenv1]
;;%{
  (list (fn[_fcenvs_ xarg0](_ats2cljpre_ML_list0_patsfun_70 (ATSCCget_1 _fcenvs_) (ATSCCget_2 _fcenvs_) xarg0)) xenv0 xenv1)
;;%}
) ;; end-of-defn


(defn
_ats2cljpre_ML_list0_patsfun_71__closurerize[xenv0]
;;%{
  (list (fn[_fcenvs_ xarg0](_ats2cljpre_ML_list0_patsfun_71 (ATSCCget_1 _fcenvs_) xarg0)) xenv0)
;;%}
) ;; end-of-defn


(defn
_ats2cljpre_ML_list0_patsfun_73__73__1__closurerize[]
;;%{
  (list (fn[_fcenvs_ xarg0](_ats2cljpre_ML_list0_patsfun_73__73__1 xarg0)))
;;%}
) ;; end-of-defn


(defn
_ats2cljpre_ML_list0_patsfun_78__closurerize[xenv0 xenv1]
;;%{
  (list (fn[_fcenvs_ xarg0](_ats2cljpre_ML_list0_patsfun_78 (ATSCCget_1 _fcenvs_) (ATSCCget_2 _fcenvs_) xarg0)) xenv0 xenv1)
;;%}
) ;; end-of-defn


(defn
_ats2cljpre_ML_list0_patsfun_79__closurerize[xenv0]
;;%{
  (list (fn[_fcenvs_ xarg0](_ats2cljpre_ML_list0_patsfun_79 (ATSCCget_1 _fcenvs_) xarg0)) xenv0)
;;%}
) ;; end-of-defn


(defn
_ats2cljpre_ML_list0_patsfun_80__closurerize[xenv0]
;;%{
  (list (fn[_fcenvs_ xarg0](_ats2cljpre_ML_list0_patsfun_80 (ATSCCget_1 _fcenvs_) xarg0)) xenv0)
;;%}
) ;; end-of-defn


(defn
_ats2cljpre_ML_list0_patsfun_73__73__2__closurerize[]
;;%{
  (list (fn[_fcenvs_ xarg0](_ats2cljpre_ML_list0_patsfun_73__73__2 xarg0)))
;;%}
) ;; end-of-defn


;;fun
(defn
 ats2cljpre_ML_list0_head_opt[arg0]
(
with-local-vars
[
;;knd = 0
  tmpret4 nil
  tmp5 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_head_opt
  (let[
    casefnx
    (fn casefnx[tmplab](case tmplab
      ;; ATSbranchseq_beg
      1 (do
       (if (ATSCKptriscons arg0)
         (casefnx 4)
         (do
          (casefnx 2)
         )
       )
      ) ;; end-of-branch
      2 (do
       atscc2clj_null
      ) ;; end-of-branch
      ;; ATSbranchseq_end
      ;; ATSbranchseq_beg
      3 (do
       (casefnx 4)
      ) ;; end-of-branch
      4 (do
       (ATSINStmpset tmp5 (ATSSELcon arg0 0))
       (ATSPMVtysum @tmp5)
      ) ;; end-of-branch
      ;; ATSbranchseq_end
      ;; (else (atscc2clj_caseof_deadcode _FILE_ _LINE_))
     ) ;; end-of-case
    ) ;; end-of-casefnx
   ] (casefnx 1)
  ) ;; end-of-let(casefnx)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_tail_opt[arg0]
(
with-local-vars
[
;;knd = 0
  tmpret7 nil
  tmp9 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_tail_opt
  (let[
    casefnx
    (fn casefnx[tmplab](case tmplab
      ;; ATSbranchseq_beg
      1 (do
       (if (ATSCKptriscons arg0)
         (casefnx 4)
         (do
          (casefnx 2)
         )
       )
      ) ;; end-of-branch
      2 (do
       atscc2clj_null
      ) ;; end-of-branch
      ;; ATSbranchseq_end
      ;; ATSbranchseq_beg
      3 (do
       (casefnx 4)
      ) ;; end-of-branch
      4 (do
       (ATSINStmpset tmp9 (ATSSELcon arg0 1))
       (ATSPMVtysum @tmp9)
      ) ;; end-of-branch
      ;; ATSbranchseq_end
      ;; (else (atscc2clj_caseof_deadcode _FILE_ _LINE_))
     ) ;; end-of-case
    ) ;; end-of-casefnx
   ] (casefnx 1)
  ) ;; end-of-let(casefnx)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_length[arg0]
(
with-local-vars
[
;;knd = 0
  tmpret10 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_length
  (ats2cljpre_list_length arg0)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_last_opt[arg0]
(
with-local-vars
[
;;knd = 0
  tmpret11 nil
  tmp15 nil
  tmp16 nil
  tmp17 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_last_opt
  (let[
    casefnx
    (fn casefnx[tmplab](case tmplab
      ;; ATSbranchseq_beg
      1 (do
       (if (ATSCKptriscons arg0)
         (casefnx 4)
         (do
          (casefnx 2)
         )
       )
      ) ;; end-of-branch
      2 (do
       atscc2clj_null
      ) ;; end-of-branch
      ;; ATSbranchseq_end
      ;; ATSbranchseq_beg
      3 (do
       (casefnx 4)
      ) ;; end-of-branch
      4 (do
       (ATSINStmpset tmp15 (ATSSELcon arg0 0))
       (ATSINStmpset tmp16 (ATSSELcon arg0 1))
       (ATSINStmpset tmp17 (_ats2cljpre_ML_list0_loop_7 @tmp15 @tmp16))
       (ATSPMVtysum @tmp17)
      ) ;; end-of-branch
      ;; ATSbranchseq_end
      ;; (else (atscc2clj_caseof_deadcode _FILE_ _LINE_))
     ) ;; end-of-case
    ) ;; end-of-casefnx
   ] (casefnx 1)
  ) ;; end-of-let(casefnx)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_loop_7[arg0 arg1]
(
with-local-vars
[
;;knd = 1
;;apy0 nil
;;apy1 nil
  tmpret12 nil
  tmp13 nil
  tmp14 nil
;;var funlab_clj
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;while(true){
   (loop [
     arg0 arg0
     arg1 arg1
    ] ; funlab_clj = 0;
    ;; __patsflab__ats2cljpre_ML_list0_loop_7
    (let[
      casefnx
      (fn casefnx[tmplab](case tmplab
        ;; ATSbranchseq_beg
        1 (do
         (if (ATSCKptriscons arg1)
           (casefnx 4)
           (do
            (casefnx 2)
           )
         )
        ) ;; end-of-branch
        2 (do
         arg0
        ) ;; end-of-branch
        ;; ATSbranchseq_end
        ;; ATSbranchseq_beg
        3 (do
         (casefnx 4)
        ) ;; end-of-branch
        4 (do
         (ATSINStmpset tmp13 (ATSSELcon arg1 0))
         (ATSINStmpset tmp14 (ATSSELcon arg1 1))
         ;; apy0 = @tmp13
         ;; apy1 = @tmp14
         ;; arg0 = apy0
         ;; arg1 = apy1
         ;; funlab_clj = 1; // __patsflab__ats2cljpre_ML_list0_loop_7
         (_ats2cljpre_ML_list0_loop_7 @tmp13 @tmp14)
        ) ;; end-of-branch
        ;; ATSbranchseq_end
        ;; (else (atscc2clj_caseof_deadcode _FILE_ _LINE_))
       ) ;; end-of-case
      ) ;; end-of-casefnx
     ] (casefnx 1)
    ) ;; end-of-let(casefnx)
    ;; if (funlab_clj > 0) continue; else ;; return tmpret12;
  ) ;} // endwhile-fun
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_get_at_opt[arg0 arg1]
(
with-local-vars
[
;;knd = 1
;;apy0 nil
;;apy1 nil
  tmpret18 nil
  tmp19 nil
  tmp20 nil
  tmp21 nil
  tmp22 nil
;;var funlab_clj
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;while(true){
   (loop [
     arg0 arg0
     arg1 arg1
    ] ; funlab_clj = 0;
    ;; __patsflab_list0_get_at_opt
    (let[
      casefnx
      (fn casefnx[tmplab](case tmplab
        ;; ATSbranchseq_beg
        1 (do
         (if (ATSCKptriscons arg0)
           (casefnx 4)
           (do
            (casefnx 2)
           )
         )
        ) ;; end-of-branch
        2 (do
         atscc2clj_null
        ) ;; end-of-branch
        ;; ATSbranchseq_end
        ;; ATSbranchseq_beg
        3 (do
         (casefnx 4)
        ) ;; end-of-branch
        4 (do
         (ATSINStmpset tmp19 (ATSSELcon arg0 0))
         (ATSINStmpset tmp20 (ATSSELcon arg0 1))
         (ATSINStmpset tmp21 (ats2cljpre_gt_int1_int1 arg1 0))
         (if @tmp21
           (do
            (ATSINStmpset tmp22 (ats2cljpre_sub_int1_int1 arg1 1))
            ;; apy0 = @tmp20
            ;; apy1 = @tmp22
            ;; arg0 = apy0
            ;; arg1 = apy1
            ;; funlab_clj = 1; // __patsflab_list0_get_at_opt
            (ats2cljpre_ML_list0_get_at_opt @tmp20 @tmp22)
           ) ;; if-then
           (do
            (ATSPMVtysum @tmp19)
           ) ;; if-else
         )
        ) ;; end-of-branch
        ;; ATSbranchseq_end
        ;; (else (atscc2clj_caseof_deadcode _FILE_ _LINE_))
       ) ;; end-of-case
      ) ;; end-of-casefnx
     ] (casefnx 1)
    ) ;; end-of-let(casefnx)
    ;; if (funlab_clj > 0) continue; else ;; return tmpret18;
  ) ;} // endwhile-fun
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_make_intrange_2[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret23 nil
  tmp24 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_make_intrange_2
  (ATSINStmpset tmp24 (ats2cljpre_list_make_intrange_2 arg0 arg1))
  @tmp24
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_make_intrange_3[arg0 arg1 arg2]
(
with-local-vars
[
;;knd = 0
  tmpret25 nil
  tmp26 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_make_intrange_3
  (ATSINStmpset tmp26 (ats2cljpre_list_make_intrange_3 arg0 arg1 arg2))
  @tmp26
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_snoc[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret38 nil
  tmp39 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_snoc
  (ATSINStmpset tmp39 (ats2cljpre_list_snoc arg0 arg1))
  @tmp39
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_extend[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret40 nil
  tmp41 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_extend
  (ATSINStmpset tmp41 (ats2cljpre_list_extend arg0 arg1))
  @tmp41
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_append[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret42 nil
  tmp43 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_append
  (ATSINStmpset tmp43 (ats2cljpre_list_append arg0 arg1))
  @tmp43
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_reverse[arg0]
(
with-local-vars
[
;;knd = 0
  tmpret44 nil
  tmp45 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_reverse
  (ATSINStmpset tmp45 (ats2cljpre_list_reverse arg0))
  @tmp45
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_reverse_append[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret46 nil
  tmp47 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_reverse_append
  (ATSINStmpset tmp47 (ats2cljpre_list_reverse_append arg0 arg1))
  @tmp47
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_concat[arg0]
(
with-local-vars
[
;;knd = 0
  tmpret48 nil
  tmp49 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_concat
  (ATSINStmpset tmp49 (ats2cljpre_list_concat arg0))
  @tmp49
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_remove_at_opt[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret50 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_remove_at_opt
  (_ats2cljpre_ML_list0_aux_23 arg0 0)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_aux_23[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret51 nil
  tmp52 nil
  tmp53 nil
  tmp54 nil
  tmp55 nil
  tmp56 nil
  tmp57 nil
  tmp58 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_aux_23
  (let[
    casefnx
    (fn casefnx[tmplab](case tmplab
      ;; ATSbranchseq_beg
      1 (do
       (if (ATSCKptriscons arg0)
         (casefnx 4)
         (do
          (casefnx 2)
         )
       )
      ) ;; end-of-branch
      2 (do
       atscc2clj_null
      ) ;; end-of-branch
      ;; ATSbranchseq_end
      ;; ATSbranchseq_beg
      3 (do
       (casefnx 4)
      ) ;; end-of-branch
      4 (do
       (ATSINStmpset tmp52 (ATSSELcon arg0 0))
       (ATSINStmpset tmp53 (ATSSELcon arg0 1))
       (ATSINStmpset tmp54 (ats2cljpre_gt_int1_int1 arg1 0))
       (if @tmp54
         (do
          (ATSINStmpset tmp56 (ats2cljpre_sub_int1_int1 arg1 1))
          (ATSINStmpset tmp55 (_ats2cljpre_ML_list0_aux_23 @tmp53 @tmp56))
          (let[
            casefnx
            (fn casefnx[tmplab](case tmplab
              ;; ATSbranchseq_beg
              1 (do
               (if (ATSCKptriscons @tmp55)
                 (casefnx 4)
                 (do
                  (casefnx 2)
                 )
               )
              ) ;; end-of-branch
              2 (do
               atscc2clj_null
              ) ;; end-of-branch
              ;; ATSbranchseq_end
              ;; ATSbranchseq_beg
              3 (do
               (casefnx 4)
              ) ;; end-of-branch
              4 (do
               (ATSINStmpset tmp57 (ATSSELcon @tmp55 0))
               (ATSINStmpset tmp58 (ATSPMVtysum @tmp52 @tmp57))
               (ATSPMVtysum @tmp58)
              ) ;; end-of-branch
              ;; ATSbranchseq_end
              ;; (else (atscc2clj_caseof_deadcode _FILE_ _LINE_))
             ) ;; end-of-case
            ) ;; end-of-casefnx
           ] (casefnx 1)
          ) ;; end-of-let(casefnx)
         ) ;; if-then
         (do
          (ATSPMVtysum @tmp53)
         ) ;; if-else
       )
      ) ;; end-of-branch
      ;; ATSbranchseq_end
      ;; (else (atscc2clj_caseof_deadcode _FILE_ _LINE_))
     ) ;; end-of-case
    ) ;; end-of-casefnx
   ] (casefnx 1)
  ) ;; end-of-let(casefnx)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_exists[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret59 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_exists
  (ats2cljpre_list_exists arg0 arg1)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_exists_method[arg0]
(
with-local-vars
[
;;knd = 0
  tmpret60 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_exists_method
  (_ats2cljpre_ML_list0_patsfun_26__closurerize arg0)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_patsfun_26[env0 arg0]
(
with-local-vars
[
;;knd = 0
  tmpret61 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_patsfun_26
  (ats2cljpre_ML_list0_exists env0 arg0)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_iexists[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret62 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_iexists
  (ats2cljpre_list_iexists arg0 arg1)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_iexists_method[arg0]
(
with-local-vars
[
;;knd = 0
  tmpret63 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_iexists_method
  (_ats2cljpre_ML_list0_patsfun_29__closurerize arg0)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_patsfun_29[env0 arg0]
(
with-local-vars
[
;;knd = 0
  tmpret64 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_patsfun_29
  (ats2cljpre_ML_list0_iexists env0 arg0)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_forall[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret65 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_forall
  (ats2cljpre_list_forall arg0 arg1)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_forall_method[arg0]
(
with-local-vars
[
;;knd = 0
  tmpret66 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_forall_method
  (_ats2cljpre_ML_list0_patsfun_32__closurerize arg0)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_patsfun_32[env0 arg0]
(
with-local-vars
[
;;knd = 0
  tmpret67 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_patsfun_32
  (ats2cljpre_ML_list0_forall env0 arg0)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_iforall[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret68 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_iforall
  (ats2cljpre_list_iforall arg0 arg1)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_iforall_method[arg0]
(
with-local-vars
[
;;knd = 0
  tmpret69 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_iforall_method
  (_ats2cljpre_ML_list0_patsfun_35__closurerize arg0)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_patsfun_35[env0 arg0]
(
with-local-vars
[
;;knd = 0
  tmpret70 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_patsfun_35
  (ats2cljpre_ML_list0_iforall env0 arg0)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_app[arg0 arg1]
(
with-local-vars
[
;;knd = 0
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_app
  (ATSINSmove1_void (ats2cljpre_ML_list0_foreach arg0 arg1))
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_foreach[arg0 arg1]
(
with-local-vars
[
;;knd = 0
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_foreach
  (ATSINSmove1_void (ats2cljpre_list_foreach arg0 arg1))
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_foreach_method[arg0]
(
with-local-vars
[
;;knd = 0
  tmpret73 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_foreach_method
  (_ats2cljpre_ML_list0_patsfun_39__closurerize arg0)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_patsfun_39[env0 arg0]
(
with-local-vars
[
;;knd = 0
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_patsfun_39
  (ATSINSmove1_void (ats2cljpre_ML_list0_foreach env0 arg0))
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_iforeach[arg0 arg1]
(
with-local-vars
[
;;knd = 0
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_iforeach
  (ATSINSmove1_void (ats2cljpre_list_iforeach arg0 arg1))
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_iforeach_method[arg0]
(
with-local-vars
[
;;knd = 0
  tmpret76 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_iforeach_method
  (_ats2cljpre_ML_list0_patsfun_42__closurerize arg0)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_patsfun_42[env0 arg0]
(
with-local-vars
[
;;knd = 0
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_patsfun_42
  (ATSINSmove1_void (ats2cljpre_ML_list0_iforeach env0 arg0))
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_rforeach[arg0 arg1]
(
with-local-vars
[
;;knd = 0
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_rforeach
  (ATSINSmove1_void (ats2cljpre_list_rforeach arg0 arg1))
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_rforeach_method[arg0]
(
with-local-vars
[
;;knd = 0
  tmpret79 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_rforeach_method
  (_ats2cljpre_ML_list0_patsfun_45__closurerize arg0)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_patsfun_45[env0 arg0]
(
with-local-vars
[
;;knd = 0
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_patsfun_45
  (ATSINSmove1_void (ats2cljpre_ML_list0_rforeach env0 arg0))
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_filter[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret81 nil
  tmp82 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_filter
  (ATSINStmpset tmp82 (ats2cljpre_list_filter arg0 arg1))
  @tmp82
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_filter_method[arg0]
(
with-local-vars
[
;;knd = 0
  tmpret83 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_filter_method
  (_ats2cljpre_ML_list0_patsfun_48__closurerize arg0)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_patsfun_48[env0 arg0]
(
with-local-vars
[
;;knd = 0
  tmpret84 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_patsfun_48
  (ats2cljpre_ML_list0_filter env0 arg0)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_map[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret85 nil
  tmp86 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_map
  (ATSINStmpset tmp86 (ats2cljpre_list_map arg0 arg1))
  @tmp86
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_map_method[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret87 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_map_method
  (_ats2cljpre_ML_list0_patsfun_51__closurerize arg0)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_patsfun_51[env0 arg0]
(
with-local-vars
[
;;knd = 0
  tmpret88 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_patsfun_51
  (ats2cljpre_ML_list0_map env0 arg0)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_mapcons[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret89 nil
  tmp90 nil
  tmp91 nil
  tmp92 nil
  tmp93 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_mapcons
  (let[
    casefnx
    (fn casefnx[tmplab](case tmplab
      ;; ATSbranchseq_beg
      1 (do
       (if (ATSCKptriscons arg1)
         (casefnx 4)
         (do
          (casefnx 2)
         )
       )
      ) ;; end-of-branch
      2 (do
       atscc2clj_null
      ) ;; end-of-branch
      ;; ATSbranchseq_end
      ;; ATSbranchseq_beg
      3 (do
       (casefnx 4)
      ) ;; end-of-branch
      4 (do
       (ATSINStmpset tmp90 (ATSSELcon arg1 0))
       (ATSINStmpset tmp91 (ATSSELcon arg1 1))
       (ATSINStmpset tmp92 (ATSPMVtysum arg0 @tmp90))
       (ATSINStmpset tmp93 (ats2cljpre_ML_list0_mapcons arg0 @tmp91))
       (ATSPMVtysum @tmp92 @tmp93)
      ) ;; end-of-branch
      ;; ATSbranchseq_end
      ;; (else (atscc2clj_caseof_deadcode _FILE_ _LINE_))
     ) ;; end-of-case
    ) ;; end-of-casefnx
   ] (casefnx 1)
  ) ;; end-of-let(casefnx)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_find_opt[arg0 arg1]
(
with-local-vars
[
;;knd = 1
;;apy0 nil
;;apy1 nil
  tmpret94 nil
  tmp95 nil
  tmp96 nil
  tmp97 nil
;;var funlab_clj
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;while(true){
   (loop [
     arg0 arg0
     arg1 arg1
    ] ; funlab_clj = 0;
    ;; __patsflab_list0_find_opt
    (let[
      casefnx
      (fn casefnx[tmplab](case tmplab
        ;; ATSbranchseq_beg
        1 (do
         (if (ATSCKptriscons arg0)
           (casefnx 4)
           (do
            (casefnx 2)
           )
         )
        ) ;; end-of-branch
        2 (do
         atscc2clj_null
        ) ;; end-of-branch
        ;; ATSbranchseq_end
        ;; ATSbranchseq_beg
        3 (do
         (casefnx 4)
        ) ;; end-of-branch
        4 (do
         (ATSINStmpset tmp95 (ATSSELcon arg0 0))
         (ATSINStmpset tmp96 (ATSSELcon arg0 1))
         (ATSINStmpset tmp97 ((ATSfunclo_fclo arg1) arg1 @tmp95))
         (if @tmp97
           (do
            (ATSPMVtysum @tmp95)
           ) ;; if-then
           (do
            ;; apy0 = @tmp96
            ;; apy1 = arg1
            ;; arg0 = apy0
            ;; arg1 = apy1
            ;; funlab_clj = 1; // __patsflab_list0_find_opt
            (ats2cljpre_ML_list0_find_opt @tmp96 arg1)
           ) ;; if-else
         )
        ) ;; end-of-branch
        ;; ATSbranchseq_end
        ;; (else (atscc2clj_caseof_deadcode _FILE_ _LINE_))
       ) ;; end-of-case
      ) ;; end-of-casefnx
     ] (casefnx 1)
    ) ;; end-of-let(casefnx)
    ;; if (funlab_clj > 0) continue; else ;; return tmpret94;
  ) ;} // endwhile-fun
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_zip[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret98 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_zip
  (_ats2cljpre_ML_list0_aux_55 arg0 arg1)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_aux_55[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret99 nil
  tmp100 nil
  tmp101 nil
  tmp102 nil
  tmp103 nil
  tmp104 nil
  tmp105 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_aux_55
  (let[
    casefnx
    (fn casefnx[tmplab](case tmplab
      ;; ATSbranchseq_beg
      1 (do
       (if (ATSCKptriscons arg0)
         (casefnx 4)
         (do
          (casefnx 2)
         )
       )
      ) ;; end-of-branch
      2 (do
       atscc2clj_null
      ) ;; end-of-branch
      ;; ATSbranchseq_end
      ;; ATSbranchseq_beg
      3 (do
       (casefnx 4)
      ) ;; end-of-branch
      4 (do
       (ATSINStmpset tmp100 (ATSSELcon arg0 0))
       (ATSINStmpset tmp101 (ATSSELcon arg0 1))
       (let[
         casefnx
         (fn casefnx[tmplab](case tmplab
           ;; ATSbranchseq_beg
           1 (do
            (if (ATSCKptriscons arg1)
              (casefnx 4)
              (do
               (casefnx 2)
              )
            )
           ) ;; end-of-branch
           2 (do
            atscc2clj_null
           ) ;; end-of-branch
           ;; ATSbranchseq_end
           ;; ATSbranchseq_beg
           3 (do
            (casefnx 4)
           ) ;; end-of-branch
           4 (do
            (ATSINStmpset tmp102 (ATSSELcon arg1 0))
            (ATSINStmpset tmp103 (ATSSELcon arg1 1))
            (ATSINStmpset tmp104 (ATSPMVtyrec @tmp100 @tmp102))
            (ATSINStmpset tmp105 (_ats2cljpre_ML_list0_aux_55 @tmp101 @tmp103))
            (ATSPMVtysum @tmp104 @tmp105)
           ) ;; end-of-branch
           ;; ATSbranchseq_end
           ;; (else (atscc2clj_caseof_deadcode _FILE_ _LINE_))
          ) ;; end-of-case
         ) ;; end-of-casefnx
        ] (casefnx 1)
       ) ;; end-of-let(casefnx)
      ) ;; end-of-branch
      ;; ATSbranchseq_end
      ;; (else (atscc2clj_caseof_deadcode _FILE_ _LINE_))
     ) ;; end-of-case
    ) ;; end-of-casefnx
   ] (casefnx 1)
  ) ;; end-of-let(casefnx)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_zipwith[arg0 arg1 arg2]
(
with-local-vars
[
;;knd = 0
  tmpret106 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_zipwith
  (_ats2cljpre_ML_list0_aux_57 arg0 arg1 arg2)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_aux_57[arg0 arg1 arg2]
(
with-local-vars
[
;;knd = 0
  tmpret107 nil
  tmp108 nil
  tmp109 nil
  tmp110 nil
  tmp111 nil
  tmp112 nil
  tmp113 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_aux_57
  (let[
    casefnx
    (fn casefnx[tmplab](case tmplab
      ;; ATSbranchseq_beg
      1 (do
       (if (ATSCKptriscons arg0)
         (casefnx 4)
         (do
          (casefnx 2)
         )
       )
      ) ;; end-of-branch
      2 (do
       atscc2clj_null
      ) ;; end-of-branch
      ;; ATSbranchseq_end
      ;; ATSbranchseq_beg
      3 (do
       (casefnx 4)
      ) ;; end-of-branch
      4 (do
       (ATSINStmpset tmp108 (ATSSELcon arg0 0))
       (ATSINStmpset tmp109 (ATSSELcon arg0 1))
       (let[
         casefnx
         (fn casefnx[tmplab](case tmplab
           ;; ATSbranchseq_beg
           1 (do
            (if (ATSCKptriscons arg1)
              (casefnx 4)
              (do
               (casefnx 2)
              )
            )
           ) ;; end-of-branch
           2 (do
            atscc2clj_null
           ) ;; end-of-branch
           ;; ATSbranchseq_end
           ;; ATSbranchseq_beg
           3 (do
            (casefnx 4)
           ) ;; end-of-branch
           4 (do
            (ATSINStmpset tmp110 (ATSSELcon arg1 0))
            (ATSINStmpset tmp111 (ATSSELcon arg1 1))
            (ATSINStmpset tmp112 ((ATSfunclo_fclo arg2) arg2 @tmp108 @tmp110))
            (ATSINStmpset tmp113 (_ats2cljpre_ML_list0_aux_57 @tmp109 @tmp111 arg2))
            (ATSPMVtysum @tmp112 @tmp113)
           ) ;; end-of-branch
           ;; ATSbranchseq_end
           ;; (else (atscc2clj_caseof_deadcode _FILE_ _LINE_))
          ) ;; end-of-case
         ) ;; end-of-casefnx
        ] (casefnx 1)
       ) ;; end-of-let(casefnx)
      ) ;; end-of-branch
      ;; ATSbranchseq_end
      ;; (else (atscc2clj_caseof_deadcode _FILE_ _LINE_))
     ) ;; end-of-case
    ) ;; end-of-casefnx
   ] (casefnx 1)
  ) ;; end-of-let(casefnx)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_zipwith_method[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret114 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_zipwith_method
  (_ats2cljpre_ML_list0_patsfun_59__closurerize arg0 arg1)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_patsfun_59[env0 env1 arg0]
(
with-local-vars
[
;;knd = 0
  tmpret115 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_patsfun_59
  (ats2cljpre_ML_list0_zipwith env0 env1 arg0)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_foldleft[arg0 arg1 arg2]
(
with-local-vars
[
;;knd = 0
  tmpret116 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_foldleft
  (_ats2cljpre_ML_list0_aux_61 arg2 arg1 arg0)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_aux_61[env0 arg0 arg1]
(
with-local-vars
[
;;knd = 1
;;apy0 nil
;;apy1 nil
  tmpret117 nil
  tmp118 nil
  tmp119 nil
  tmp120 nil
;;var funlab_clj
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;while(true){
   (loop [
     env0 env0
     arg0 arg0
     arg1 arg1
    ] ; funlab_clj = 0;
    ;; __patsflab__ats2cljpre_ML_list0_aux_61
    (let[
      casefnx
      (fn casefnx[tmplab](case tmplab
        ;; ATSbranchseq_beg
        1 (do
         (if (ATSCKptriscons arg1)
           (casefnx 4)
           (do
            (casefnx 2)
           )
         )
        ) ;; end-of-branch
        2 (do
         arg0
        ) ;; end-of-branch
        ;; ATSbranchseq_end
        ;; ATSbranchseq_beg
        3 (do
         (casefnx 4)
        ) ;; end-of-branch
        4 (do
         (ATSINStmpset tmp118 (ATSSELcon arg1 0))
         (ATSINStmpset tmp119 (ATSSELcon arg1 1))
         (ATSINStmpset tmp120 ((ATSfunclo_fclo env0) env0 arg0 @tmp118))
         ;; apy0 = @tmp120
         ;; apy1 = @tmp119
         ;; arg0 = apy0
         ;; arg1 = apy1
         ;; funlab_clj = 1; // __patsflab__ats2cljpre_ML_list0_aux_61
         (_ats2cljpre_ML_list0_aux_61 env0 @tmp120 @tmp119)
        ) ;; end-of-branch
        ;; ATSbranchseq_end
        ;; (else (atscc2clj_caseof_deadcode _FILE_ _LINE_))
       ) ;; end-of-case
      ) ;; end-of-casefnx
     ] (casefnx 1)
    ) ;; end-of-let(casefnx)
    ;; if (funlab_clj > 0) continue; else ;; return tmpret117;
  ) ;} // endwhile-fun
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_foldright[arg0 arg1 arg2]
(
with-local-vars
[
;;knd = 0
  tmpret121 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_foldright
  (_ats2cljpre_ML_list0_aux_63 arg1 arg2 arg0 arg2)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_aux_63[env0 env1 arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret122 nil
  tmp123 nil
  tmp124 nil
  tmp125 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_aux_63
  (let[
    casefnx
    (fn casefnx[tmplab](case tmplab
      ;; ATSbranchseq_beg
      1 (do
       (if (ATSCKptriscons arg0)
         (casefnx 4)
         (do
          (casefnx 2)
         )
       )
      ) ;; end-of-branch
      2 (do
       arg1
      ) ;; end-of-branch
      ;; ATSbranchseq_end
      ;; ATSbranchseq_beg
      3 (do
       (casefnx 4)
      ) ;; end-of-branch
      4 (do
       (ATSINStmpset tmp123 (ATSSELcon arg0 0))
       (ATSINStmpset tmp124 (ATSSELcon arg0 1))
       (ATSINStmpset tmp125 (_ats2cljpre_ML_list0_aux_63 env0 env1 @tmp124 env1))
       ((ATSfunclo_fclo env0) env0 @tmp123 @tmp125)
      ) ;; end-of-branch
      ;; ATSbranchseq_end
      ;; (else (atscc2clj_caseof_deadcode _FILE_ _LINE_))
     ) ;; end-of-case
    ) ;; end-of-casefnx
   ] (casefnx 1)
  ) ;; end-of-let(casefnx)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_list0_sort_2[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret128 nil
  tmp129 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_list0_sort_2
  (ATSINStmpset tmp129 (ats2cljpre_list_sort_2 arg0 arg1))
  @tmp129
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_streamize_list0_zip[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret130 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_streamize_list0_zip
  (ats2cljpre_streamize_list_zip arg0 arg1)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_streamize_list0_cross[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret131 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_streamize_list0_cross
  (ats2cljpre_streamize_list_cross arg0 arg1)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_streamize_list0_nchoose[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret132 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_streamize_list0_nchoose
  (_ats2cljpre_ML_list0_auxmain_69 arg0 arg1)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_auxmain_69[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret133 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_auxmain_69
  (ATSPMVllazyval (_ats2cljpre_ML_list0_patsfun_70__closurerize arg0 arg1))
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_patsfun_70[env0 env1 arg0]
(
with-local-vars
[
;;knd = 0
  tmpret134 nil
  tmp135 nil
  tmp136 nil
  tmp137 nil
  tmp138 nil
  tmp139 nil
  tmp140 nil
  tmp141 nil
  tmp142 nil
  tmp144 nil
  tmp145 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_patsfun_70
  (if arg0
    (do
     (ATSINStmpset tmp135 (ats2cljpre_gt_int1_int1 env1 0))
     (if @tmp135
       (do
        (let[
          casefnx
          (fn casefnx[tmplab](case tmplab
            ;; ATSbranchseq_beg
            1 (do
             (if (ATSCKptriscons env0)
               (casefnx 4)
               (do
                (casefnx 2)
               )
             )
            ) ;; end-of-branch
            2 (do
             atscc2clj_null
            ) ;; end-of-branch
            ;; ATSbranchseq_end
            ;; ATSbranchseq_beg
            3 (do
             (casefnx 4)
            ) ;; end-of-branch
            4 (do
             (ATSINStmpset tmp136 (ATSSELcon env0 0))
             (ATSINStmpset tmp137 (ATSSELcon env0 1))
             (ATSINStmpset tmp139 (ats2cljpre_sub_int1_int1 env1 1))
             (ATSINStmpset tmp138 (_ats2cljpre_ML_list0_auxmain_69 @tmp137 @tmp139))
             (ATSINStmpset tmp140 (_ats2cljpre_ML_list0_auxmain_69 @tmp137 env1))
             (ATSINStmpset tmp142 (ats2cljpre_stream_vt_map_cloref @tmp138 (_ats2cljpre_ML_list0_patsfun_71__closurerize @tmp136)))
             (ATSINStmpset tmp141 (ats2cljpre_stream_vt_append @tmp142 @tmp140))
             (ATSPMVllazyval_eval @tmp141)
            ) ;; end-of-branch
            ;; ATSbranchseq_end
            ;; (else (atscc2clj_caseof_deadcode _FILE_ _LINE_))
           ) ;; end-of-case
          ) ;; end-of-casefnx
         ] (casefnx 1)
        ) ;; end-of-let(casefnx)
       ) ;; if-then
       (do
        (ATSINStmpset tmp144 atscc2clj_null)
        (ATSINStmpset tmp145 (ats2cljpre_stream_vt_make_nil__72__1))
        (ATSPMVtysum @tmp144 @tmp145)
       ) ;; if-else
     )
    ) ;; if-then
    (do
    ) ;; if-else
  )
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_patsfun_71[env0 arg0]
(
with-local-vars
[
;;knd = 0
  tmpret143 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_patsfun_71
  (ATSPMVtysum env0 arg0)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_stream_vt_make_nil__72__1[]
(
with-local-vars
[
;;knd = 0
  tmpret146__1 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_stream_vt_make_nil
  (ATSPMVllazyval (_ats2cljpre_ML_list0_patsfun_73__73__1__closurerize))
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_patsfun_73__73__1[arg0]
(
with-local-vars
[
;;knd = 0
  tmpret147__1 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_patsfun_73
  (if arg0
    (do
     atscc2clj_null
    ) ;; if-then
    (do
    ) ;; if-else
  )
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_ML_streamize_list0_nchoose_rest[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret150 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_streamize_list0_nchoose_rest
  (_ats2cljpre_ML_list0_auxmain_77 arg0 arg1)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_auxmain_77[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmpret151 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_auxmain_77
  (ATSPMVllazyval (_ats2cljpre_ML_list0_patsfun_78__closurerize arg0 arg1))
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_patsfun_78[env0 env1 arg0]
(
with-local-vars
[
;;knd = 0
  tmpret152 nil
  tmp153 nil
  tmp154 nil
  tmp155 nil
  tmp156 nil
  tmp157 nil
  tmp158 nil
  tmp159 nil
  tmp160 nil
  tmp163 nil
  tmp166 nil
  tmp167 nil
  tmp168 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_patsfun_78
  (if arg0
    (do
     (ATSINStmpset tmp153 (ats2cljpre_gt_int1_int1 env1 0))
     (if @tmp153
       (do
        (let[
          casefnx
          (fn casefnx[tmplab](case tmplab
            ;; ATSbranchseq_beg
            1 (do
             (if (ATSCKptriscons env0)
               (casefnx 4)
               (do
                (casefnx 2)
               )
             )
            ) ;; end-of-branch
            2 (do
             atscc2clj_null
            ) ;; end-of-branch
            ;; ATSbranchseq_end
            ;; ATSbranchseq_beg
            3 (do
             (casefnx 4)
            ) ;; end-of-branch
            4 (do
             (ATSINStmpset tmp154 (ATSSELcon env0 0))
             (ATSINStmpset tmp155 (ATSSELcon env0 1))
             (ATSINStmpset tmp157 (ats2cljpre_sub_int1_int1 env1 1))
             (ATSINStmpset tmp156 (_ats2cljpre_ML_list0_auxmain_77 @tmp155 @tmp157))
             (ATSINStmpset tmp158 (_ats2cljpre_ML_list0_auxmain_77 @tmp155 env1))
             (ATSINStmpset tmp160 (ats2cljpre_stream_vt_map_cloref @tmp156 (_ats2cljpre_ML_list0_patsfun_79__closurerize @tmp154)))
             (ATSINStmpset tmp163 (ats2cljpre_stream_vt_map_cloref @tmp158 (_ats2cljpre_ML_list0_patsfun_80__closurerize @tmp154)))
             (ATSINStmpset tmp159 (ats2cljpre_stream_vt_append @tmp160 @tmp163))
             (ATSPMVllazyval_eval @tmp159)
            ) ;; end-of-branch
            ;; ATSbranchseq_end
            ;; (else (atscc2clj_caseof_deadcode _FILE_ _LINE_))
           ) ;; end-of-case
          ) ;; end-of-casefnx
         ] (casefnx 1)
        ) ;; end-of-let(casefnx)
       ) ;; if-then
       (do
        (ATSINStmpset tmp167 atscc2clj_null)
        (ATSINStmpset tmp166 (ATSPMVtyrec @tmp167 env0))
        (ATSINStmpset tmp168 (ats2cljpre_stream_vt_make_nil__72__2))
        (ATSPMVtysum @tmp166 @tmp168)
       ) ;; if-else
     )
    ) ;; if-then
    (do
    ) ;; if-else
  )
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_patsfun_79[env0 arg0]
(
with-local-vars
[
;;knd = 0
  tmpret161 nil
  tmp162 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_patsfun_79
  (ATSINStmpset tmp162 (ATSPMVtysum env0 (ATSSELboxrec arg0 0)))
  (ATSPMVtyrec @tmp162 (ATSSELboxrec arg0 1))
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_patsfun_80[env0 arg0]
(
with-local-vars
[
;;knd = 0
  tmpret164 nil
  tmp165 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_patsfun_80
  (ATSINStmpset tmp165 (ATSPMVtysum env0 (ATSSELboxrec arg0 1)))
  (ATSPMVtyrec (ATSSELboxrec arg0 0) @tmp165)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 ats2cljpre_stream_vt_make_nil__72__2[]
(
with-local-vars
[
;;knd = 0
  tmpret146__2 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_stream_vt_make_nil
  (ATSPMVllazyval (_ats2cljpre_ML_list0_patsfun_73__73__2__closurerize))
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 _ats2cljpre_ML_list0_patsfun_73__73__2[arg0]
(
with-local-vars
[
;;knd = 0
  tmpret147__2 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab__ats2cljpre_ML_list0_patsfun_73
  (if arg0
    (do
     atscc2clj_null
    ) ;; if-then
    (do
    ) ;; if-else
  )
) ;; end-of-with-local-vars
) ;; end-of-fun

;;;;;;
;;
;; end-of-compilation-unit
;;
;;;;;;
