#
# A simple Makefile
# for generating libtutorats0
#

######

PATSOPT=$(PATSHOME)/bin/patsopt
ATSCC2PHP=$(PATSHOME)/bin/atscc2php

######

CPF=cp -f
RMF=rm -f
RMRF=rm -rf

######

###### end of [Makefile] ######
