#
# For generating libatscc2php
#

######

PATSOPT=$(PATSHOME)/bin/patsopt
ATSCC2PHP=$(PATSHOME)/bin/atscc2php

######

CPF=cp -f

######

all:: ; \
$(PATSOPT) -d ./PHP/DATS/patsopt.dats | $(ATSCC2PHP) -o ./output/PHP/DATS/patsopt_dats.php -i

#######

###### end of [Makefile] ######
