######
#
#
JAVAC=javac
#
#
######

all:: \
int_cats
int_cats: \
CATS/int_cats.java; $(JAVAC) -d ./classes $<

all:: \
bool_cats
bool_cats: \
CATS/int_cats.java; $(JAVAC) -d ./classes $<

######

###### end of [Makefile] ######
