/*
**
** The JavaScript code is generated by atscc2js
** The starting compilation time is: 2015-8-5: 14h: 5m
**
*/

// ATSassume(_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__card_type)

// ATSassume(_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__cardset_type)

function
f_29__closurerize(env0, env1, env2, env3)
{
  return [function(cenv, arg0) { return f_29(cenv[1], cenv[2], cenv[3], cenv[4], arg0); }, env0, env1, env2, env3];
}


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__card_get_val(arg0)
{
//
// knd = 0
  var tmpret0
  var tmplab, tmplab_js
//
  // __patsflab_card_get_val
  tmpret0 = arg0[0];
  return tmpret0;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__card_make_int(arg0)
{
//
// knd = 0
  var tmpret1
  var tmp2
  var tmp3
  var tmplab, tmplab_js
//
  // __patsflab_card_make_int
  tmp2 = ats2jspre_int2double(arg0);
  tmp3 = [0, arg0];
  tmpret1 = [tmp2, tmp3];
  return tmpret1;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__add_card_card(arg0, arg1)
{
//
// knd = 0
  var tmpret4
  var tmp5
  var tmp6
  var tmplab, tmplab_js
//
  // __patsflab_add_card_card
  tmp5 = ats2jspre_add_double_double(arg0[0], arg1[0]);
  tmp6 = [1, arg0, arg1];
  tmpret4 = [tmp5, tmp6];
  return tmpret4;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__sub_card_card(arg0, arg1)
{
//
// knd = 0
  var tmpret7
  var tmp8
  var tmp9
  var tmplab, tmplab_js
//
  // __patsflab_sub_card_card
  tmp8 = ats2jspre_sub_double_double(arg0[0], arg1[0]);
  tmp9 = [2, arg0, arg1];
  tmpret7 = [tmp8, tmp9];
  return tmpret7;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__mul_card_card(arg0, arg1)
{
//
// knd = 0
  var tmpret10
  var tmp11
  var tmp12
  var tmplab, tmplab_js
//
  // __patsflab_mul_card_card
  tmp11 = ats2jspre_mul_double_double(arg0[0], arg1[0]);
  tmp12 = [3, arg0, arg1];
  tmpret10 = [tmp11, tmp12];
  return tmpret10;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__div_card_card(arg0, arg1)
{
//
// knd = 0
  var tmpret13
  var tmp14
  var tmp15
  var tmplab, tmplab_js
//
  // __patsflab_div_card_card
  tmp14 = ats2jspre_div_double_double(arg0[0], arg1[0]);
  tmp15 = [4, arg0, arg1];
  tmpret13 = [tmp14, tmp15];
  return tmpret13;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fprint_card(arg0, arg1)
{
//
// knd = 0
  var tmp17
  var tmp18
  var tmp19
  var tmp20
  var tmp21
  var tmp22
  var tmp23
  var tmp24
  var tmp25
  var tmplab, tmplab_js
//
  // __patsflab_fprint_card
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab0
      if(!ATSCKpat_con1(arg1[1], 0)) { tmplab_js = 3; break; }
      case 2: // __atstmplab1
      tmp17 = arg1[1][1];
      ats2nodejs_fprint_string(arg0, "CARDint(");
      ats2nodejs_fprint_int(arg0, tmp17);
      ats2nodejs_fprint_string(arg0, ")");
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab2
      if(!ATSCKpat_con1(arg1[1], 1)) { tmplab_js = 5; break; }
      case 4: // __atstmplab3
      tmp18 = arg1[1][1];
      tmp19 = arg1[1][2];
      ats2nodejs_fprint_string(arg0, "CARDadd(");
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fprint_card(arg0, tmp18);
      ats2nodejs_fprint_string(arg0, ", ");
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fprint_card(arg0, tmp19);
      ats2nodejs_fprint_string(arg0, ")");
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 5: // __atstmplab4
      if(!ATSCKpat_con1(arg1[1], 2)) { tmplab_js = 7; break; }
      case 6: // __atstmplab5
      tmp20 = arg1[1][1];
      tmp21 = arg1[1][2];
      ats2nodejs_fprint_string(arg0, "CARDsub(");
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fprint_card(arg0, tmp20);
      ats2nodejs_fprint_string(arg0, ", ");
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fprint_card(arg0, tmp21);
      ats2nodejs_fprint_string(arg0, ")");
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 7: // __atstmplab6
      if(!ATSCKpat_con1(arg1[1], 3)) { tmplab_js = 9; break; }
      case 8: // __atstmplab7
      tmp22 = arg1[1][1];
      tmp23 = arg1[1][2];
      ats2nodejs_fprint_string(arg0, "CARDmul(");
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fprint_card(arg0, tmp22);
      ats2nodejs_fprint_string(arg0, ", ");
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fprint_card(arg0, tmp23);
      ats2nodejs_fprint_string(arg0, ")");
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 9: // __atstmplab8
      case 10: // __atstmplab9
      tmp24 = arg1[1][1];
      tmp25 = arg1[1][2];
      ats2nodejs_fprint_string(arg0, "CARDdiv(");
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fprint_card(arg0, tmp24);
      ats2nodejs_fprint_string(arg0, ", ");
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fprint_card(arg0, tmp25);
      ats2nodejs_fprint_string(arg0, ")");
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fpprint_card(arg0, arg1)
{
//
// knd = 0
  var tmp55
  var tmp56
  var tmp57
  var tmp58
  var tmp59
  var tmp60
  var tmp61
  var tmp62
  var tmp63
  var tmplab, tmplab_js
//
  // __patsflab_fpprint_card
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab20
      if(!ATSCKpat_con1(arg1[1], 0)) { tmplab_js = 3; break; }
      case 2: // __atstmplab21
      tmp55 = arg1[1][1];
      ats2nodejs_fprint_int(arg0, tmp55);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab22
      if(!ATSCKpat_con1(arg1[1], 1)) { tmplab_js = 5; break; }
      case 4: // __atstmplab23
      tmp56 = arg1[1][1];
      tmp57 = arg1[1][2];
      ats2nodejs_fprint_string(arg0, "(");
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fpprint_card(arg0, tmp56);
      ats2nodejs_fprint_string(arg0, " + ");
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fpprint_card(arg0, tmp57);
      ats2nodejs_fprint_string(arg0, ")");
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 5: // __atstmplab24
      if(!ATSCKpat_con1(arg1[1], 2)) { tmplab_js = 7; break; }
      case 6: // __atstmplab25
      tmp58 = arg1[1][1];
      tmp59 = arg1[1][2];
      ats2nodejs_fprint_string(arg0, "(");
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fpprint_card(arg0, tmp58);
      ats2nodejs_fprint_string(arg0, " - ");
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fpprint_card(arg0, tmp59);
      ats2nodejs_fprint_string(arg0, ")");
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 7: // __atstmplab26
      if(!ATSCKpat_con1(arg1[1], 3)) { tmplab_js = 9; break; }
      case 8: // __atstmplab27
      tmp60 = arg1[1][1];
      tmp61 = arg1[1][2];
      ats2nodejs_fprint_string(arg0, "(");
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fpprint_card(arg0, tmp60);
      ats2nodejs_fprint_string(arg0, " * ");
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fpprint_card(arg0, tmp61);
      ats2nodejs_fprint_string(arg0, ")");
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 9: // __atstmplab28
      case 10: // __atstmplab29
      tmp62 = arg1[1][1];
      tmp63 = arg1[1][2];
      ats2nodejs_fprint_string(arg0, "(");
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fpprint_card(arg0, tmp62);
      ats2nodejs_fprint_string(arg0, " / ");
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fpprint_card(arg0, tmp63);
      ats2nodejs_fprint_string(arg0, ")");
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__cardset_size(arg0)
{
//
// knd = 0
  var tmpret80
  var tmplab, tmplab_js
//
  // __patsflab_cardset_size
  tmpret80 = ats2jspre_JSarray_length(arg0);
  return tmpret80;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__cardset_make_list(arg0)
{
//
// knd = 0
  var tmpret81
  var tmp86
  var tmplab, tmplab_js
//
  // __patsflab_cardset_make_list
  tmp86 = ats2jspre_JSarray_nil();
  tmpret81 = loop_12(tmp86, arg0);
  return tmpret81;
} // end-of-function


function
loop_12(arg0, arg1)
{
//
// knd = 1
  var apy0
  var apy1
  var tmpret82
  var tmp83
  var tmp84
  var tmp85
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_loop_12
    // ATScaseofseq_beg
    tmplab_js = 1;
    while(true) {
      tmplab = tmplab_js; tmplab_js = 0;
      switch(tmplab) {
        // ATSbranchseq_beg
        case 1: // __atstmplab30
        if(ATSCKptriscons(arg1)) { tmplab_js = 4; break; }
        case 2: // __atstmplab31
        tmpret82 = arg0;
        break;
        // ATSbranchseq_end
        // ATSbranchseq_beg
        case 3: // __atstmplab32
        case 4: // __atstmplab33
        tmp83 = arg1[0];
        tmp84 = arg1[1];
        tmp85 = ats2jspre_JSarray_push(arg0, tmp83);
        // ATStailcalseq_beg
        apy0 = arg0;
        apy1 = tmp84;
        arg0 = apy0;
        arg1 = apy1;
        funlab_js = 1; // __patsflab_loop_12
        // ATStailcalseq_end
        break;
        // ATSbranchseq_end
      } // end-of-switch
      if (tmplab_js === 0) break;
    } // endwhile
    // ATScaseofseq_end
    if (funlab_js > 0) continue; else return tmpret82;
  } // endwhile-fun
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__cardset_get_at(arg0, arg1)
{
//
// knd = 0
  var tmpret87
  var tmplab, tmplab_js
//
  // __patsflab_cardset_get_at
  tmpret87 = ats2jspre_JSarray_get_at(arg0, arg1);
  return tmpret87;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__cardset_remove2_add1(arg0, arg1, arg2, arg3)
{
//
// knd = 0
  var tmpret88
  var tmp90
  var tmp92
  var tmp93
  var tmp96
  var tmplab, tmplab_js
//
  // __patsflab_cardset_remove2_add1
  tmp90 = ats2jspre_gte_int1_int1(arg1, 0);
  ats2jspre_assert_errmsg_bool1(tmp90, "/home/hwxi/research/Postiats-contrib/git/projects/SMALL/GameOf24/JavaScript/GameOf24_js.dats: 3936(line=241, offs=10) -- 3954(line=241, offs=28)");
  tmp92 = ats2jspre_gte_int1_int1(arg2, arg1);
  ats2jspre_assert_errmsg_bool1(tmp92, "/home/hwxi/research/Postiats-contrib/git/projects/SMALL/GameOf24/JavaScript/GameOf24_js.dats: 3964(line=242, offs=10) -- 3982(line=242, offs=28)");
  tmp93 = ats2jspre_JSarray_copy(arg0);
  ats2jspre_JSarray_remove_at(tmp93, arg2);
  ats2jspre_JSarray_remove_at(tmp93, arg1);
  tmp96 = ats2jspre_JSarray_push(tmp93, arg3);
  tmpret88 = tmp93;
  return tmpret88;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fpprint_cardlst(arg0, arg1)
{
//
// knd = 1
  var apy0
  var apy1
  var tmp113
  var tmp114
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_fpprint_cardlst
    // ATScaseofseq_beg
    tmplab_js = 1;
    while(true) {
      tmplab = tmplab_js; tmplab_js = 0;
      switch(tmplab) {
        // ATSbranchseq_beg
        case 1: // __atstmplab38
        if(ATSCKptriscons(arg1)) { tmplab_js = 4; break; }
        case 2: // __atstmplab39
        // ATSINSmove_void
        break;
        // ATSbranchseq_end
        // ATSbranchseq_beg
        case 3: // __atstmplab40
        case 4: // __atstmplab41
        tmp113 = arg1[0];
        tmp114 = arg1[1];
        fprone_18(arg0, tmp113);
        // ATStailcalseq_beg
        apy0 = arg0;
        apy1 = tmp114;
        arg0 = apy0;
        arg1 = apy1;
        funlab_js = 1; // __patsflab_fpprint_cardlst
        // ATStailcalseq_end
        break;
        // ATSbranchseq_end
      } // end-of-switch
      if (tmplab_js === 0) break;
    } // endwhile
    // ATScaseofseq_end
    if (funlab_js > 0) continue; else return/*_void*/;
  } // endwhile-fun
} // end-of-function


function
fprone_18(arg0, arg1)
{
//
// knd = 0
  var tmp107
  var tmp111
  var tmp112
  var tmplab, tmplab_js
//
  // __patsflab_fprone_18
  tmp107 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__card_get_val(arg1);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fpprint_card(arg0, arg1);
  ats2nodejs_fprint_string(arg0, " = ");
  tmp112 = ats2jspre_add_double_double(tmp107, 0.100000000000000006);
  tmp111 = ats2jspre_double2int(tmp112);
  ats2nodejs_fprint_int(arg0, tmp111);
  ats2nodejs_fprint_newline(arg0);
  return/*_void*/;
} // end-of-function


function
is0_19(arg0)
{
//
// knd = 0
  var tmpret116
  var tmp117
  var tmplab, tmplab_js
//
  // __patsflab_is0_19
  tmp117 = ats2jspre_abs_double(arg0);
  tmpret116 = ats2jspre_lt_double_double(tmp117, 0.000000010000000000);
  return tmpret116;
} // end-of-function


function
isn0_20(arg0)
{
//
// knd = 0
  var tmpret118
  var tmp119
  var tmplab, tmplab_js
//
  // __patsflab_isn0_20
  tmp119 = ats2jspre_abs_double(arg0);
  tmpret118 = ats2jspre_gte_double_double(tmp119, 0.000000010000000000);
  return tmpret118;
} // end-of-function


function
is24_21(arg0)
{
//
// knd = 0
  var tmpret120
  var tmp121
  var tmp122
  var tmplab, tmplab_js
//
  // __patsflab_is24_21
  tmp122 = ats2jspre_sub_double_double(arg0, 24.0);
  tmp121 = ats2jspre_abs_double(tmp122);
  tmpret120 = ats2jspre_lt_double_double(tmp121, 0.000000010000000000);
  return tmpret120;
} // end-of-function


function
card_isneqz_22(arg0)
{
//
// knd = 0
  var tmpret123
  var tmp124
  var tmplab, tmplab_js
//
  // __patsflab_card_isneqz_22
  tmp124 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__card_get_val(arg0);
  tmpret123 = isn0_20(tmp124);
  return tmpret123;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_dats__task_reduce(arg0, arg1)
{
//
// knd = 0
  var tmpret125
  var tmp157
  var tmplab, tmplab_js
//
  // __patsflab_task_reduce
  tmp157 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__cardset_size(arg0);
  tmpret125 = loop1_25(arg0, tmp157, 0, arg1);
  return tmpret125;
} // end-of-function


function
auxdo_24(arg0, arg1, arg2, arg3)
{
//
// knd = 0
  var tmpret126
  var tmp127
  var tmp128
  var tmp129
  var tmp130
  var tmp131
  var tmp132
  var tmp133
  var tmp134
  var tmp135
  var tmp136
  var tmp137
  var tmp138
  var tmp139
  var tmp140
  var tmp141
  var tmp142
  var tmp143
  var tmp144
  var tmp145
  var tmp146
  var tmp147
  var tmplab, tmplab_js
//
  // __patsflab_auxdo_24
  tmp127 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__cardset_get_at(arg0, arg1);
  tmp128 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__cardset_get_at(arg0, arg2);
  tmp131 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__add_card_card(tmp127, tmp128);
  tmp130 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__cardset_remove2_add1(arg0, arg1, arg2, tmp131);
  tmp129 = [tmp130, arg3];
  tmp134 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__sub_card_card(tmp127, tmp128);
  tmp133 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__cardset_remove2_add1(arg0, arg1, arg2, tmp134);
  tmp132 = [tmp133, tmp129];
  tmp137 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__sub_card_card(tmp128, tmp127);
  tmp136 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__cardset_remove2_add1(arg0, arg1, arg2, tmp137);
  tmp135 = [tmp136, tmp132];
  tmp140 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__mul_card_card(tmp127, tmp128);
  tmp139 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__cardset_remove2_add1(arg0, arg1, arg2, tmp140);
  tmp138 = [tmp139, tmp135];
  tmp142 = card_isneqz_22(tmp128);
  if(tmp142) {
    tmp144 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__div_card_card(tmp127, tmp128);
    tmp143 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__cardset_remove2_add1(arg0, arg1, arg2, tmp144);
    tmp141 = [tmp143, tmp138];
  } else {
    tmp141 = tmp138;
  } // endif
  tmp145 = card_isneqz_22(tmp127);
  if(tmp145) {
    tmp147 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__div_card_card(tmp128, tmp127);
    tmp146 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__cardset_remove2_add1(arg0, arg1, arg2, tmp147);
    tmpret126 = [tmp146, tmp141];
  } else {
    tmpret126 = tmp141;
  } // endif
  return tmpret126;
} // end-of-function


function
loop1_25(arg0, arg1, arg2, arg3)
{
//
// knd = 2
  var apy0
  var apy1
  var apy2
  var apy3
  var tmpret148
  var tmp149
  var tmp150
  var tmp151
  var a2rg0
  var a2rg1
  var a2rg2
  var a2rg3
  var a2rg4
  var a2py0
  var a2py1
  var a2py2
  var a2py3
  var a2py4
  var tmpret152
  var tmp153
  var tmp154
  var tmp155
  var tmp156
  var funlab_js
  var tmplab, tmplab_js
//
  funlab_js = 1;
  while(true) {
    switch(funlab_js) {
      case 1: {
        funlab_js = 0;
        tmp150 = ats2jspre_add_int0_int0(arg2, 1);
        tmp149 = ats2jspre_lt_int0_int0(tmp150, arg1);
        if(tmp149) {
          tmp151 = ats2jspre_add_int0_int0(arg2, 1);
          // ATStailcalseq_beg
          a2py0 = arg0;
          a2py1 = arg1;
          a2py2 = arg2;
          a2py3 = tmp151;
          a2py4 = arg3;
          a2rg0 = a2py0;
          a2rg1 = a2py1;
          a2rg2 = a2py2;
          a2rg3 = a2py3;
          a2rg4 = a2py4;
          funlab_js = 2; // __patsflab_loop2_26
          // ATStailcalseq_end
        } else {
          tmpret148 = arg3;
        } // endif
        if (funlab_js > 0) continue; else return tmpret148;
      } // end-of-case
      case 2: {
        funlab_js = 0;
        tmp153 = ats2jspre_lt_int0_int0(a2rg3, a2rg1);
        if(tmp153) {
          tmp154 = auxdo_24(a2rg0, a2rg2, a2rg3, a2rg4);
          tmp155 = ats2jspre_add_int0_int0(a2rg3, 1);
          // ATStailcalseq_beg
          a2py0 = a2rg0;
          a2py1 = a2rg1;
          a2py2 = a2rg2;
          a2py3 = tmp155;
          a2py4 = tmp154;
          a2rg0 = a2py0;
          a2rg1 = a2py1;
          a2rg2 = a2py2;
          a2rg3 = a2py3;
          a2rg4 = a2py4;
          funlab_js = 2; // __patsflab_loop2_26
          // ATStailcalseq_end
        } else {
          tmp156 = ats2jspre_add_int0_int0(a2rg2, 1);
          // ATStailcalseq_beg
          apy0 = a2rg0;
          apy1 = a2rg1;
          apy2 = tmp156;
          apy3 = a2rg4;
          arg0 = apy0;
          arg1 = apy1;
          arg2 = apy2;
          arg3 = apy3;
          funlab_js = 1; // __patsflab_loop1_25
          // ATStailcalseq_end
        } // endif
        if (funlab_js > 0) continue; else return tmpret152;
      } // end-of-case
    } // end-of-switch
  } // endwhile-fun
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_dats__tasklst_reduce(arg0, arg1)
{
//
// knd = 1
  var apy0
  var apy1
  var tmpret158
  var tmp159
  var tmp160
  var tmp161
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_tasklst_reduce
    // ATScaseofseq_beg
    tmplab_js = 1;
    while(true) {
      tmplab = tmplab_js; tmplab_js = 0;
      switch(tmplab) {
        // ATSbranchseq_beg
        case 1: // __atstmplab42
        if(ATSCKptrisnull(arg0)) { tmplab_js = 4; break; }
        case 2: // __atstmplab43
        tmp159 = arg0[0];
        tmp160 = arg0[1];
        tmp161 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_dats__task_reduce(tmp159, arg1);
        // ATStailcalseq_beg
        apy0 = tmp160;
        apy1 = tmp161;
        arg0 = apy0;
        arg1 = apy1;
        funlab_js = 1; // __patsflab_tasklst_reduce
        // ATStailcalseq_end
        break;
        // ATSbranchseq_end
        // ATSbranchseq_beg
        case 3: // __atstmplab44
        case 4: // __atstmplab45
        tmpret158 = arg1;
        break;
        // ATSbranchseq_end
      } // end-of-switch
      if (tmplab_js === 0) break;
    } // endwhile
    // ATScaseofseq_end
    if (funlab_js > 0) continue; else return tmpret158;
  } // endwhile-fun
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__GameOf24_play(arg0, arg1, arg2, arg3)
{
//
// knd = 0
  var tmpret162
  var tmp163
  var tmp164
  var tmp165
  var tmp166
  var tmp168
  var tmp169
  var tmp170
  var tmp171
  var tmp172
  var tmp173
  var tmp174
  var tmp175
  var tmp176
  var tmp177
  var tmp178
  var tmp179
  var tmp180
  var tmp181
  var tmp182
  var tmp183
  var tmp184
  var tmp192
  var tmp193
  var tmplab, tmplab_js
//
  // __patsflab_GameOf24_play
  tmp163 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__card_make_int(arg0);
  tmp164 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__card_make_int(arg1);
  tmp165 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__card_make_int(arg2);
  tmp166 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__card_make_int(arg3);
  tmp172 = null;
  tmp171 = [tmp166, tmp172];
  tmp170 = [tmp165, tmp171];
  tmp169 = [tmp164, tmp170];
  tmp168 = [tmp163, tmp169];
  tmp173 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__cardset_make_list(tmp168);
  tmp175 = null;
  tmp174 = [tmp173, tmp175];
  tmp176 = null;
  tmp177 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_dats__tasklst_reduce(tmp174, tmp176);
  tmp178 = ats2jspre_list_reverse(tmp177);
  tmp179 = null;
  tmp180 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_dats__tasklst_reduce(tmp178, tmp179);
  tmp181 = ats2jspre_list_reverse(tmp180);
  tmp182 = null;
  tmp183 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_dats__tasklst_reduce(tmp181, tmp182);
  tmp184 = ats2jspre_list_reverse(tmp183);
  tmp193 = null;
  tmp192 = filter_30(tmp184, tmp193);
  tmpret162 = ats2jspre_list_reverse(tmp192);
  return tmpret162;
} // end-of-function


function
f_29(env0, env1, env2, env3, arg0)
{
//
// knd = 0
  var tmpret167
  var tmplab, tmplab_js
//
  // __patsflab_f_29
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab46
      if(!ATSCKpat_int(arg0, 0)) { tmplab_js = 3; break; }
      case 2: // __atstmplab47
      tmpret167 = env0;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab48
      if(!ATSCKpat_int(arg0, 1)) { tmplab_js = 5; break; }
      case 4: // __atstmplab49
      tmpret167 = env1;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 5: // __atstmplab50
      if(!ATSCKpat_int(arg0, 2)) { tmplab_js = 7; break; }
      case 6: // __atstmplab51
      tmpret167 = env2;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 7: // __atstmplab52
      tmpret167 = env3;
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret167;
} // end-of-function


function
filter_30(arg0, arg1)
{
//
// knd = 1
  var apy0
  var apy1
  var tmpret185
  var tmp186
  var tmp187
  var tmp188
  var tmp189
  var tmp190
  var tmp191
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_filter_30
    // ATScaseofseq_beg
    tmplab_js = 1;
    while(true) {
      tmplab = tmplab_js; tmplab_js = 0;
      switch(tmplab) {
        // ATSbranchseq_beg
        case 1: // __atstmplab53
        if(ATSCKptriscons(arg0)) { tmplab_js = 4; break; }
        case 2: // __atstmplab54
        tmpret185 = arg1;
        break;
        // ATSbranchseq_end
        // ATSbranchseq_beg
        case 3: // __atstmplab55
        case 4: // __atstmplab56
        tmp186 = arg0[0];
        tmp187 = arg0[1];
        tmp188 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__cardset_get_at(tmp186, 0);
        tmp189 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__card_get_val(tmp188);
        tmp191 = is24_21(tmp189);
        if(tmp191) {
          tmp190 = [tmp188, arg1];
        } else {
          tmp190 = arg1;
        } // endif
        // ATStailcalseq_beg
        apy0 = tmp187;
        apy1 = tmp190;
        arg0 = apy0;
        arg1 = apy1;
        funlab_js = 1; // __patsflab_filter_30
        // ATStailcalseq_end
        break;
        // ATSbranchseq_end
      } // end-of-switch
      if (tmplab_js === 0) break;
    } // endwhile
    // ATScaseofseq_end
    if (funlab_js > 0) continue; else return tmpret185;
  } // endwhile-fun
} // end-of-function


function
GameOf24_play2(arg0, arg1, arg2, arg3)
{
//
// knd = 0
  var tmpret194
  var tmp195
  var tmp199
  var tmplab, tmplab_js
//
  // __patsflab_GameOf24_play2
  tmp195 = ats2jspre_JSarray_nil();
  tmp199 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__GameOf24_play(arg0, arg1, arg2, arg3);
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab57
      if(ATSCKptriscons(tmp199)) { tmplab_js = 4; break; }
      case 2: // __atstmplab58
      tmpret194 = "No solution is found.";
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab59
      case 4: // __atstmplab60
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__logats_cardlst__15__1(tmp195, tmp199);
      tmpret194 = ats2jspre_JSarray_join_sep(tmp195, "");
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret194;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__logats_cardlst__15__1(env0, arg0)
{
//
// knd = 1
  var apy0
  var tmp102__1
  var tmp103__1
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_logats_cardlst
    // ATScaseofseq_beg
    tmplab_js = 1;
    while(true) {
      tmplab = tmplab_js; tmplab_js = 0;
      switch(tmplab) {
        // ATSbranchseq_beg
        case 1: // __atstmplab34
        if(ATSCKptriscons(arg0)) { tmplab_js = 4; break; }
        case 2: // __atstmplab35
        // ATSINSmove_void
        break;
        // ATSbranchseq_end
        // ATSbranchseq_beg
        case 3: // __atstmplab36
        case 4: // __atstmplab37
        tmp102__1 = arg0[0];
        tmp103__1 = arg0[1];
        auxone_16__16__1(env0, tmp102__1);
        // ATStailcalseq_beg
        apy0 = tmp103__1;
        arg0 = apy0;
        funlab_js = 1; // __patsflab_logats_cardlst
        // ATStailcalseq_end
        break;
        // ATSbranchseq_end
      } // end-of-switch
      if (tmplab_js === 0) break;
    } // endwhile
    // ATScaseofseq_end
    if (funlab_js > 0) continue; else return/*_void*/;
  } // endwhile-fun
} // end-of-function


function
auxone_16__16__1(env0, arg0)
{
//
// knd = 0
  var tmp99__1
  var tmp100__1
  var tmp101__1
  var tmplab, tmplab_js
//
  // __patsflab_auxone_16
  tmp99__1 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__card_get_val(arg0);
  tmp101__1 = ats2jspre_add_double_double(tmp99__1, 0.100000000000000006);
  tmp100__1 = ats2jspre_double2int(tmp101__1);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats4__36__1(env0, arg0, " = ", tmp100__1, "\n");
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats4__36__1(env0, arg0, arg1, arg2, arg3)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_logats4
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__33__1(env0, arg0);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__14(env0, arg1);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__15(env0, arg2);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__16(env0, arg3);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__33__1(env0, arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_logats_tmp
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__logats_card__7__1(env0, arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__logats_card__7__1(env0, arg0)
{
//
// knd = 0
  var tmp45__1
  var tmp46__1
  var tmp47__1
  var tmp48__1
  var tmp49__1
  var tmp50__1
  var tmp51__1
  var tmp52__1
  var tmp53__1
  var tmplab, tmplab_js
//
  // __patsflab_logats_card
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab10
      if(!ATSCKpat_con1(arg0[1], 0)) { tmplab_js = 3; break; }
      case 2: // __atstmplab11
      tmp45__1 = arg0[1][1];
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats1__40__1(env0, tmp45__1);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab12
      if(!ATSCKpat_con1(arg0[1], 1)) { tmplab_js = 5; break; }
      case 4: // __atstmplab13
      tmp46__1 = arg0[1][1];
      tmp47__1 = arg0[1][2];
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats5__43__1(env0, "(", tmp46__1, " + ", tmp47__1, ")");
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 5: // __atstmplab14
      if(!ATSCKpat_con1(arg0[1], 2)) { tmplab_js = 7; break; }
      case 6: // __atstmplab15
      tmp48__1 = arg0[1][1];
      tmp49__1 = arg0[1][2];
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats5__43__2(env0, "(", tmp48__1, " - ", tmp49__1, ")");
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 7: // __atstmplab16
      if(!ATSCKpat_con1(arg0[1], 3)) { tmplab_js = 9; break; }
      case 8: // __atstmplab17
      tmp50__1 = arg0[1][1];
      tmp51__1 = arg0[1][2];
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats5__43__3(env0, "(", tmp50__1, " * ", tmp51__1, ")");
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 9: // __atstmplab18
      case 10: // __atstmplab19
      tmp52__1 = arg0[1][1];
      tmp53__1 = arg0[1][2];
      _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats5__43__4(env0, "(", tmp52__1, " / ", tmp53__1, ")");
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats1__40__1(env0, arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_logats1
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__1(env0, arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__1(env0, arg0)
{
//
// knd = 0
  var tmp197__1
  var tmplab, tmplab_js
//
  // __patsflab_logats_tmp
  tmp197__1 = ats2jspre_JSarray_push(env0, arg0);
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats5__43__1(env0, arg0, arg1, arg2, arg3, arg4)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_logats5
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__2(env0, arg0);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__logats_card__7__1(env0, arg1);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__3(env0, arg2);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__logats_card__7__1(env0, arg3);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__4(env0, arg4);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__2(env0, arg0)
{
//
// knd = 0
  var tmp197__2
  var tmplab, tmplab_js
//
  // __patsflab_logats_tmp
  tmp197__2 = ats2jspre_JSarray_push(env0, arg0);
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__3(env0, arg0)
{
//
// knd = 0
  var tmp197__3
  var tmplab, tmplab_js
//
  // __patsflab_logats_tmp
  tmp197__3 = ats2jspre_JSarray_push(env0, arg0);
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__4(env0, arg0)
{
//
// knd = 0
  var tmp197__4
  var tmplab, tmplab_js
//
  // __patsflab_logats_tmp
  tmp197__4 = ats2jspre_JSarray_push(env0, arg0);
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats5__43__2(env0, arg0, arg1, arg2, arg3, arg4)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_logats5
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__5(env0, arg0);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__logats_card__7__1(env0, arg1);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__6(env0, arg2);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__logats_card__7__1(env0, arg3);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__7(env0, arg4);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__5(env0, arg0)
{
//
// knd = 0
  var tmp197__5
  var tmplab, tmplab_js
//
  // __patsflab_logats_tmp
  tmp197__5 = ats2jspre_JSarray_push(env0, arg0);
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__6(env0, arg0)
{
//
// knd = 0
  var tmp197__6
  var tmplab, tmplab_js
//
  // __patsflab_logats_tmp
  tmp197__6 = ats2jspre_JSarray_push(env0, arg0);
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__7(env0, arg0)
{
//
// knd = 0
  var tmp197__7
  var tmplab, tmplab_js
//
  // __patsflab_logats_tmp
  tmp197__7 = ats2jspre_JSarray_push(env0, arg0);
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats5__43__3(env0, arg0, arg1, arg2, arg3, arg4)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_logats5
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__8(env0, arg0);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__logats_card__7__1(env0, arg1);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__9(env0, arg2);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__logats_card__7__1(env0, arg3);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__10(env0, arg4);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__8(env0, arg0)
{
//
// knd = 0
  var tmp197__8
  var tmplab, tmplab_js
//
  // __patsflab_logats_tmp
  tmp197__8 = ats2jspre_JSarray_push(env0, arg0);
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__9(env0, arg0)
{
//
// knd = 0
  var tmp197__9
  var tmplab, tmplab_js
//
  // __patsflab_logats_tmp
  tmp197__9 = ats2jspre_JSarray_push(env0, arg0);
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__10(env0, arg0)
{
//
// knd = 0
  var tmp197__10
  var tmplab, tmplab_js
//
  // __patsflab_logats_tmp
  tmp197__10 = ats2jspre_JSarray_push(env0, arg0);
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats5__43__4(env0, arg0, arg1, arg2, arg3, arg4)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_logats5
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__11(env0, arg0);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__logats_card__7__1(env0, arg1);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__12(env0, arg2);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__logats_card__7__1(env0, arg3);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__13(env0, arg4);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__11(env0, arg0)
{
//
// knd = 0
  var tmp197__11
  var tmplab, tmplab_js
//
  // __patsflab_logats_tmp
  tmp197__11 = ats2jspre_JSarray_push(env0, arg0);
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__12(env0, arg0)
{
//
// knd = 0
  var tmp197__12
  var tmplab, tmplab_js
//
  // __patsflab_logats_tmp
  tmp197__12 = ats2jspre_JSarray_push(env0, arg0);
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__13(env0, arg0)
{
//
// knd = 0
  var tmp197__13
  var tmplab, tmplab_js
//
  // __patsflab_logats_tmp
  tmp197__13 = ats2jspre_JSarray_push(env0, arg0);
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__14(env0, arg0)
{
//
// knd = 0
  var tmp197__14
  var tmplab, tmplab_js
//
  // __patsflab_logats_tmp
  tmp197__14 = ats2jspre_JSarray_push(env0, arg0);
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__15(env0, arg0)
{
//
// knd = 0
  var tmp197__15
  var tmplab, tmplab_js
//
  // __patsflab_logats_tmp
  tmp197__15 = ats2jspre_JSarray_push(env0, arg0);
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_contrib_057_libatscc_057_libatscc2js_057_basics_js_056_sats__logats_tmp__32__16(env0, arg0)
{
//
// knd = 0
  var tmp197__16
  var tmplab, tmplab_js
//
  // __patsflab_logats_tmp
  tmp197__16 = ats2jspre_JSarray_push(env0, arg0);
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
GameOf24_js_main0_js()
{
//
// knd = 0
  var tmp288
  var tmp300
  var tmp312
  var tmp324
  var tmplab, tmplab_js
//
  // __patsflab_main0_js
  tmp288 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__GameOf24_play(3, 3, 8, 8);
  ats2nodejs_fprint_string(ats2nodejs_process_stdout, "play(");
  ats2nodejs_fprint_int(ats2nodejs_process_stdout, 3);
  ats2nodejs_fprint_string(ats2nodejs_process_stdout, ", ");
  ats2nodejs_fprint_int(ats2nodejs_process_stdout, 3);
  ats2nodejs_fprint_string(ats2nodejs_process_stdout, ", ");
  ats2nodejs_fprint_int(ats2nodejs_process_stdout, 8);
  ats2nodejs_fprint_string(ats2nodejs_process_stdout, ", ");
  ats2nodejs_fprint_int(ats2nodejs_process_stdout, 8);
  ats2nodejs_fprint_string(ats2nodejs_process_stdout, "):");
  ats2nodejs_fprint_newline(ats2nodejs_process_stdout);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fpprint_cardlst(ats2nodejs_process_stdout, tmp288);
  tmp300 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__GameOf24_play(4, 4, 10, 10);
  ats2nodejs_fprint_string(ats2nodejs_process_stdout, "play(");
  ats2nodejs_fprint_int(ats2nodejs_process_stdout, 4);
  ats2nodejs_fprint_string(ats2nodejs_process_stdout, ", ");
  ats2nodejs_fprint_int(ats2nodejs_process_stdout, 4);
  ats2nodejs_fprint_string(ats2nodejs_process_stdout, ", ");
  ats2nodejs_fprint_int(ats2nodejs_process_stdout, 10);
  ats2nodejs_fprint_string(ats2nodejs_process_stdout, ", ");
  ats2nodejs_fprint_int(ats2nodejs_process_stdout, 10);
  ats2nodejs_fprint_string(ats2nodejs_process_stdout, "):");
  ats2nodejs_fprint_newline(ats2nodejs_process_stdout);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fpprint_cardlst(ats2nodejs_process_stdout, tmp300);
  tmp312 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__GameOf24_play(5, 5, 7, 11);
  ats2nodejs_fprint_string(ats2nodejs_process_stdout, "play(");
  ats2nodejs_fprint_int(ats2nodejs_process_stdout, 5);
  ats2nodejs_fprint_string(ats2nodejs_process_stdout, ", ");
  ats2nodejs_fprint_int(ats2nodejs_process_stdout, 5);
  ats2nodejs_fprint_string(ats2nodejs_process_stdout, ", ");
  ats2nodejs_fprint_int(ats2nodejs_process_stdout, 7);
  ats2nodejs_fprint_string(ats2nodejs_process_stdout, ", ");
  ats2nodejs_fprint_int(ats2nodejs_process_stdout, 11);
  ats2nodejs_fprint_string(ats2nodejs_process_stdout, "):");
  ats2nodejs_fprint_newline(ats2nodejs_process_stdout);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fpprint_cardlst(ats2nodejs_process_stdout, tmp312);
  tmp324 = _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__GameOf24_play(3, 5, 7, 13);
  ats2nodejs_fprint_string(ats2nodejs_process_stdout, "play(");
  ats2nodejs_fprint_int(ats2nodejs_process_stdout, 3);
  ats2nodejs_fprint_string(ats2nodejs_process_stdout, ", ");
  ats2nodejs_fprint_int(ats2nodejs_process_stdout, 5);
  ats2nodejs_fprint_string(ats2nodejs_process_stdout, ", ");
  ats2nodejs_fprint_int(ats2nodejs_process_stdout, 7);
  ats2nodejs_fprint_string(ats2nodejs_process_stdout, ", ");
  ats2nodejs_fprint_int(ats2nodejs_process_stdout, 13);
  ats2nodejs_fprint_string(ats2nodejs_process_stdout, "):");
  ats2nodejs_fprint_newline(ats2nodejs_process_stdout);
  _057_home_057_hwxi_057_research_057_Postiats_055_contrib_057_git_057_projects_057_SMALL_057_GameOf24_057_JavaScript_057_GameOf24_js_056_sats__fpprint_cardlst(ats2nodejs_process_stdout, tmp324);
  return/*_void*/;
} // end-of-function


/* ****** ****** */

/* end-of-compilation-unit */
