#
# A Simple Makefile
#

######

all:: upload_html

######
#
upload_html: ; \
  scp mytest.html ats-hwxi,ats-lang@web.sourceforge.net:htdocs/COMPILED/doc/PROJECT/MEDIUM/ATS-parse-emit/JavaScript/.
upload_DATS_JS: ; \
  scp DATS_JS/*.js ats-hwxi,ats-lang@web.sourceforge.net:htdocs/COMPILED/doc/PROJECT/MEDIUM/ATS-parse-emit/JavaScript/DATS_JS/.
#
######

###### end of [Makefile] ######
