#
# A Simple Makefile
#

######

all:: upload_html

######
#
upload_html: ; \
scp inputform.html inputform_process.php \
  ats-hwxi,ats-lang@web.sourceforge.net:htdocs/COMPILED/doc/PROJECT/SMALL/GameOf24/PHP/.
#
######

###### end of [Makefile] ######
