#
# For testing
#

######

testall:: ; $(MAKE) -C pidigits testall
testall:: ; $(MAKE) -C mandelbrot testall
testall:: ; $(MAKE) -C fasta-redux testall
testall:: ; $(MAKE) -C reverse-complement testall
testall:: ; $(MAKE) -C spectral-norm testall
testall:: ; $(MAKE) -C k-nucleotide testall

######

###### end of [Makefile] ######
