#
# This is for testing
#

######

testall:: ; $(MAKE) -C Part1 testall
testall:: ; $(MAKE) -C Part1-2 testall
testall:: ; $(MAKE) -C Part1-3 testall
testall:: ; $(MAKE) -C Part2 testall

######

###### end of [Makefile] ######
