;;;;;;
;;
;; The Clojure code is generated by atscc2clj
;; The starting compilation time is: 2016-12-25: 17h:42m
;;
;;;;;;
(declare slistref_make_nil)
(declare slistref_length)
(declare slistref_push)
(declare slistref_pop_opt)
(declare slistref_foldleft)
(declare slistref_foldright)
;;;;;;


;; ATSassume(_057_Users_057_RyanKing_057_ATS2_055_contrib_057_contrib_057_libatscc_057_libatscc2clj_057_SATS_057_slistref_056_sats__slistref_type)

;;fun
(defn
 slistref_make_nil[]
(
with-local-vars
[
;;knd = 0
  tmpret0 nil
  tmp1 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_slistref_make_nil
  (ATSINStmpset tmp1 atscc2clj_null)
  (ats2cljpre_ref @tmp1)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 slistref_length[arg0]
(
with-local-vars
[
;;knd = 0
  tmpret2 nil
  tmp3 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_slistref_length
  (ATSINStmpset tmp3 (ats2cljpre_ref_get_elt arg0))
  (ats2cljpre_list_length @tmp3)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 slistref_push[arg0 arg1]
(
with-local-vars
[
;;knd = 0
  tmp5 nil
  tmp6 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_slistref_push
  (ATSINStmpset tmp6 (ats2cljpre_ref_get_elt arg0))
  (ATSINStmpset tmp5 (ATSPMVtysum arg1 @tmp6))
  (ATSINSmove1_void (ats2cljpre_ref_set_elt arg0 @tmp5))
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 slistref_pop_opt[arg0]
(
with-local-vars
[
;;knd = 0
  tmpret7 nil
  tmp8 nil
  tmp9 nil
  tmp10 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_slistref_pop_opt
  (ATSINStmpset tmp8 (ats2cljpre_ref_get_elt arg0))
  (let[
    casefnx
    (fn casefnx[tmplab](case tmplab
      ;; ATSbranchseq_beg
      1 (do
       (if (ATSCKptriscons @tmp8)
         (casefnx 4)
         (do
          (casefnx 2)
         )
       )
      ) ;; end-of-branch
      2 (do
       atscc2clj_null
      ) ;; end-of-branch
      ;; ATSbranchseq_end
      ;; ATSbranchseq_beg
      3 (do
       (casefnx 4)
      ) ;; end-of-branch
      4 (do
       (ATSINStmpset tmp9 (ATSSELcon @tmp8 0))
       (ATSINStmpset tmp10 (ATSSELcon @tmp8 1))
       (ATSINSmove1_void (ats2cljpre_ref_set_elt arg0 @tmp10))
       (ATSPMVtysum @tmp9)
      ) ;; end-of-branch
      ;; ATSbranchseq_end
      ;; (else (atscc2clj_caseof_deadcode _FILE_ _LINE_))
     ) ;; end-of-case
    ) ;; end-of-casefnx
   ] (casefnx 1)
  ) ;; end-of-let(casefnx)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 slistref_foldleft[arg0 arg1 arg2]
(
with-local-vars
[
;;knd = 0
  tmpret12 nil
  tmp13 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_slistref_foldleft
  (ATSINStmpset tmp13 (ats2cljpre_ref_get_elt arg0))
  (ats2cljpre_list_foldleft @tmp13 arg1 arg2)
) ;; end-of-with-local-vars
) ;; end-of-fun


;;fun
(defn
 slistref_foldright[arg0 arg1 arg2]
(
with-local-vars
[
;;knd = 0
  tmpret14 nil
  tmp15 nil
;;var tmplab,tmplab_clj
] ;; with-local-vars
  ;; __patsflab_slistref_foldright
  (ATSINStmpset tmp15 (ats2cljpre_ref_get_elt arg0))
  (ats2cljpre_list_foldright @tmp15 arg1 arg2)
) ;; end-of-with-local-vars
) ;; end-of-fun

;;;;;;
;;
;; end-of-compilation-unit
;;
;;;;;;
